# This file modified from a gitlab tmeplate, located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml  
# (original license before modification: MIT)

default:
  image: python:3.10
stages:          # List of stages for jobs, and their order of execution
  #- build
  - test
  - docs

include:
- template: Security/SAST.gitlab-ci.yml

sast:
  stage: test
  artifacts: 
    paths:
      - gl-sast-report.json

build-job:
  stage: test     # build
  script:
    - python -m venv build
    - build/bin/pip install poetry
    - mkdir dist
    - build/bin/poetry build
  artifacts:
    paths:
      - dist/palmettobug-0.1.0-py3-none-any.whl
  

test-job:       # This job runs in the build stage, which runs first.
  stage: test
  before_script:
    - python -m venv testing
    - source testing/bin/activate
    - pip install -e .
    #- pip install pytest pytest-order
  script:
    # - python tests/test_fetch.py          ## only one test script at a time, until the final test of all at once
    - python tests/test_img_proc.py
    - python tests/test_analysis.py
    - python tests/test_make_px_classifier.py
    - python tests/test_spatial.py
    - pip freeze

  
# docs-job1:
#    stage: docs
#    script:
       # pseudo-code:
#      - install pandoc
#      - pandoc convert word docs --> ReST
  
# docs-job2:
#    stage: docs
#    script:
#      - python -m venv docs
#      - source testing/bin/activate
#      - pip install -e .
#      - pip install sphinx



