## built from the readthedocs template

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment: 
      - python -m pip install pip==25.1.1  

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: docs/source/requirements.txt