## built from the readthedocs template

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/source/conf.py

python:
  pre_install: 
    - python -m pip install pip==25.1.1  
  install:
    - method: pip
      path: .
    - requirements: docs/source/requirements.txt