// Note this file was generated by AI (Microsoft's Copilot) as part of attempting to port the python in palmettobug (for spaceANOVA) into Rust
// This includes porting the translations of R code (primarily spatstat) that has their own license information -- see the original spaceanova.py file inside
// PalmettoBUG and/or the Other_License_Details.txt file for information about those packages & their licenses


// AI debugging: lines of code I commented out are marked with a unique comment ID -->     //##
// search for this to find these lines for later fixing (if needed)

use numpy::{PyReadonlyArray1};
use pyo3::prelude::*;
use pyo3::types::PyDict;
use rayon::prelude::*;
use rand::prelude::*;
use rand_pcg::Pcg64Mcg;
use std::collections::HashMap;
use std::f64::consts::PI;

/// Numerical epsilon check (equivalent to numpy finfo eps logic in spirit).
#[inline]
fn is_small(x: f64) -> bool {
    x.abs() < f64::EPSILON
}

#[inline]
fn hang(d: f64, r: f64) -> f64 {
    if r > d && r > 0.0 {
        let v = (d / r).clamp(-1.0, 1.0);
        v.acos()
    } else {
        0.0
    }
}

/// Precomputed per-point geometry relative to the window for Ripley isotropic edge correction.
#[derive(Clone, Copy, Debug)]
struct PointGeom {
    d_left: f64,
    d_right: f64,
    d_up: f64,
    d_down: f64,
    corner: bool,
    ang_left_up: f64,
    ang_left_down: f64,
    ang_right_up: f64,
    ang_right_down: f64,
    ang_up_left: f64,
    ang_up_right: f64,
    ang_down_left: f64,
    ang_down_right: f64,
}

impl PointGeom {
    fn from_xy(x: f64, y: f64, xmin: f64, xmax: f64, ymin: f64, ymax: f64) -> Self {
        let d_left = x - xmin;
        let d_right = xmax - x;
        let d_up = y - ymin;
        let d_down = ymax - y;

        let corner = ((is_small(d_left) as i32)
            + (is_small(d_right) as i32)
            + (is_small(d_down) as i32)
            + (is_small(d_up) as i32))
            >= 2;

        let ang_left_up = d_up.atan2(d_left);
        let ang_left_down = d_down.atan2(d_left);
        let ang_right_up = d_up.atan2(d_right);
        let ang_right_down = d_down.atan2(d_right);
        let ang_up_left = d_left.atan2(d_up);
        let ang_up_right = d_right.atan2(d_up);
        let ang_down_left = d_left.atan2(d_down);
        let ang_down_right = d_right.atan2(d_down);

        Self {
            d_left,
            d_right,
            d_up,
            d_down,
            corner,
            ang_left_up,
            ang_left_down,
            ang_right_up,
            ang_right_down,
            ang_up_left,
            ang_up_right,
            ang_down_left,
            ang_down_right,
        }
    }

    #[inline]
    fn weight(&self, r: f64) -> f64 {
        // Four hangs depend on r
        let angle_left = hang(self.d_left, r);
        let angle_right = hang(self.d_right, r);
        let angle_down = hang(self.d_down, r);
        let angle_up = hang(self.d_up, r);

        // mins with static angles:
        let mini_left = angle_left.min(self.ang_left_up) + angle_left.min(self.ang_left_down);
        let mini_right = angle_right.min(self.ang_right_up) + angle_right.min(self.ang_right_down);
        let mini_down = angle_down.min(self.ang_down_left) + angle_down.min(self.ang_down_right);
        let mini_up = angle_up.min(self.ang_up_left) + angle_up.min(self.ang_up_right);

        let mut total = mini_left + mini_right + mini_down + mini_up;
        if self.corner {
            total += PI / 2.0;
        }

        // weight = 1 / (1 - total / (2π)), clamped to [1, 100]
        let denom = 1.0 - (total / (2.0 * PI));
        let mut w = if denom <= 0.0 { 100.0 } else { 1.0 / denom };
        if w < 1.0 {
            w = 1.0;
        } else if w > 100.0 {
            w = 100.0;
        }
        w
    }
}

#[derive(Clone, Debug)]
struct Edge {
    left: usize,
    right: usize,
    dist: f64,
    w: f64, // weight computed for 'left' point
}

/// Simple 2D grid hashing to get neighbors within new_max efficiently.
fn build_grid(
    x: &[f64],
    y: &[f64],
    xmin: f64,
    ymin: f64,
    cell: f64,
) -> HashMap<(i32, i32), Vec<usize>> {
    let mut grid: HashMap<(i32, i32), Vec<usize>> = HashMap::new();
    for (i, (&xi, &yi)) in x.iter().zip(y.iter()).enumerate() {
        let gx = ((xi - xmin) / cell).floor() as i32;
        let gy = ((yi - ymin) / cell).floor() as i32;
        grid.entry((gx, gy)).or_default().push(i);
    }
    grid
}

fn precompute_edges(
    x: &[f64],
    y: &[f64],
    geom: &[PointGeom],
    xmin: f64,
    ymin: f64,
    new_max: f64,
) -> Vec<Edge> {
    if new_max <= 0.0 {
        return Vec::new();
    }
    let cell = new_max.max(1e-9);
    let grid = build_grid(x, y, xmin, ymin, cell);
    let n = x.len();
    let new_max2 = new_max * new_max;

    // Parallel over all left points
    let chunks: Vec<Vec<Edge>> = (0..n)
        .into_par_iter()
        .map(|i| {
            let xi = x[i];
            let yi = y[i];
            let gx = ((xi - xmin) / cell).floor() as i32;
            let gy = ((yi - ymin) / cell).floor() as i32;
            let mut local: Vec<Edge> = Vec::new();

            for dx in -1..=1 {
                for dy in -1..=1 {
                    let key = (gx + dx, gy + dy);
                    if let Some(idx_list) = grid.get(&key) {
                        for &j in idx_list {
                            if j == i {
                                continue;
                            }
                            let dx = x[j] - xi;
                            let dy = y[j] - yi;
                            let d2 = dx * dx + dy * dy;
                            if d2 <= new_max2 && d2 > 0.0 {
                                let r = d2.sqrt();
                                let w = geom[i].weight(r);
                                local.push(Edge {
                                    left: i,
                                    right: j,
                                    dist: r,
                                    w,
                                });
                            }
                        }
                    }
                }
            }
            local
        })
        .collect();

    let mut edges: Vec<Edge> = Vec::new();
    edges.reserve(chunks.iter().map(|v| v.len()).sum());
    for mut v in chunks {
        edges.append(&mut v);
    }
    edges
}

/// Produce the radii vector and truncation bound.
/// Mirrors Python behavior: if diameter/2 < max_r, we truncate to the largest r < (diameter/2).
fn make_radii_with_truncation(min_r: usize, max_r: usize, step: usize, diameter: f64) -> (Vec<f64>, f64, bool) {
    let radii: Vec<f64> = (min_r..=max_r).step_by(step).map(|r| r as f64).collect();
    let bound = diameter / 2.0;
    if bound < (max_r as f64) {
        // find last r < bound
        if let Some(&last) = radii.iter().filter(|&&r| r < bound).last() {
            (radii, last, true)
        } else {
            // No radii less than bound, effective truncation removes all bins
            (radii, 0.0, true)
        }
    } else {
        (radii, max_r as f64, false)
    }
}

/// Build theoretical K as π r² with radii > new_max set to 0 (by making those radii 0).
fn theoretical_k(radii: &[f64], new_max: f64, n1: f64, n2: f64, window_area: f64) -> Vec<f64> {
    let scale = if window_area > 0.0 { n1 * n2 / window_area } else { 0.0 };
    radii.iter()
        .map(|&r| {
            if r <= new_max {
                std::f64::consts::PI * r * r * scale
            } else {
                0.0
            }
        })
        .collect()
}

#[pyfunction]
fn k_all_at_once_optimized<'py>(
    py: Python<'py>,
    x: PyReadonlyArray1<f64>,
    y: PyReadonlyArray1<f64>,
    labels: Vec<String>,
    r_min: usize,
    r_max: usize,
    r_step: usize,
    threshold: usize,
    permutations: usize,
    perm_seed: u64,
) -> PyResult<Py<PyDict>> {

    use pyo3::types::PyDict;

    // --- Load coordinate slices ---
    let x = x.as_slice()?;
    let y = y.as_slice()?;
    let labels_str: Vec<String> = labels;   // &[String]

    let n_points = x.len();
    if n_points != y.len() || n_points != labels_str.len() {
        return Err(pyo3::exceptions::PyValueError::new_err(
            "x, y, labels must have same length",
        ));
    }

    // --- Window geometry ---
    let xmin = x.iter().fold(f64::INFINITY, |a,&b| a.min(b));
    let xmax = x.iter().fold(f64::NEG_INFINITY, |a,&b| a.max(b));
    let ymin = y.iter().fold(f64::INFINITY, |a,&b| a.min(b));
    let ymax = y.iter().fold(f64::NEG_INFINITY, |a,&b| a.max(b));
    let dx = xmax - xmin;
    let dy = ymax - ymin;
    let window_area = dx * dy;
    let diameter = ((dx*dx)+(dy*dy)).sqrt();

    let (radii, new_max, _) = make_radii_with_truncation(r_min, r_max, r_step, diameter);
    let n_bins = radii.len();

    // --- Build unique labels ---
    let mut unique: Vec<String> = labels_str.to_vec();
    unique.sort();
    unique.dedup();
    let L = unique.len();

    // --- Map label string -> integer code ---
    let mut label_index: HashMap<String, usize> = HashMap::new();
    for (i, lab) in unique.iter().enumerate() {
        label_index.insert(lab.clone(), i);
    }

    // --- Convert input labels to integer codes ---
    let mut labels_int = Vec::with_capacity(labels_str.len());
    for lab in labels_str {
        labels_int.push(label_index[&lab]);  
    }

    // --- Precompute geometry + edges ---
    let geom: Vec<PointGeom> = x.iter()
        .zip(y.iter())
        .map(|(&xi,&yi)| PointGeom::from_xy(xi, yi, xmin, xmax, ymin, ymax))
        .collect();

    let edges = py.allow_threads(|| precompute_edges(x, y, &geom, xmin, ymin, new_max));

    // --- Compute effective histogram bins ---
    let lo = r_min as f64;
    let eff_bins = if r_step > 0 {
        if r_min == 0 {
            ((new_max / r_step as f64).floor() as isize).max(0) as usize
        } else {
            ((((new_max - lo) / r_step as f64).floor()) as isize).max(0) as usize
        }
    } else { 0 };

    // --- Global accumulators ---
    let mut fill = vec![0.0f64; L*L];
    let mut bins = vec![0.0f64; L*L * eff_bins];

    // --- SINGLE PASS over edges ---
    for e in &edges {
        let d = e.dist;
        if d <= 0.0 || d >= new_max { continue; }

        let li = labels_int[e.left];
        let lj = labels_int[e.right];
        let pair = li * L + lj;

        if d < lo {
            fill[pair] += e.w;
        } else if eff_bins > 0 {
            let k = ((d - lo) / (r_step as f64)).floor() as isize;
            if k >= 0 {
                let k = k as usize;
                if k < eff_bins {
                    unsafe { 
                        *bins.get_unchecked_mut(pair*eff_bins + k) += e.w;
                    }
                }
            }
        }
    }

    // --- Label counts ---
    let mut counts = vec![0usize; L];
    for &code in &labels_int {
        counts[code] += 1;
    }

    // --- Permutation accumulators ---
    let mut perm_acc = vec![vec![0.0f64; n_bins]; L*L];

    // --- Permutations ---
    if permutations > 0 {
        py.allow_threads(|| {
            let mut rng = Pcg64Mcg::seed_from_u64(perm_seed);
            let mut labels_perm = labels_int.clone();
            let mut pair_map = vec![0usize; n_points];

            for _ in 0..permutations {
                labels_perm.shuffle(&mut rng);

                // create pair_map (label code)
                for i in 0..n_points {
                    pair_map[i] = labels_perm[i];
                }

                let mut local_fill = vec![0.0f64; L*L];
                let mut local_bins = vec![0.0f64; L*L*eff_bins];

                for e in &edges {
                    let d = e.dist;
                    if d <= 0.0 || d >= new_max { continue; }

                    let i = pair_map[e.left];
                    let j = pair_map[e.right];
                    let pair = i * L + j;

                    if d < lo {
                        local_fill[pair] += e.w;
                    } else if eff_bins > 0 {
                        let k = ((d - lo) / (r_step as f64)).floor() as isize;
                        if k >= 0 {
                            let k = k as usize;
                            if k < eff_bins {
                                unsafe {
                                    *local_bins.get_unchecked_mut(pair*eff_bins + k) += e.w;
                                }
                            }
                        }
                    }
                }

                // cumulative + normalize
                for i in 0..L {
                    for j in 0..L {
                        let pair = i*L + j;
                        let n1 = counts[i];
                        let n2 = counts[j];
                        // Threshold/area gate: if invalid, leave zeros (do not add
                        if (n1 as usize) < (threshold as usize) || (n2 as usize) < (threshold as usize) {
                            continue
                        }

                        let norm = (n1 as f64) * (n2 as f64 / window_area);

                        let mut c = local_fill[pair];
                        perm_acc[pair][0] += c / norm;

                        for k in 0..eff_bins {
                            let val = local_bins[pair*eff_bins + k];
                            c += val;
                            if k+1 < n_bins {
                                perm_acc[pair][k+1] += c / norm;
                            }
                        }
                    }
                }
            }
        });

        // average
        for pair in 0..L*L {
            for b in 0..n_bins {
                perm_acc[pair][b] /= permutations as f64;
            }
        }
    }

    // --- Observed cumulative K ---
    let mut k_obs = vec![vec![0.0f64; n_bins]; L*L];

    for i in 0..L {
        for j in 0..L {
            let pair = i*L + j;

            let n1 = counts[i];
            let n2 = counts[j];
            // Threshold/area gate: if invalid, leave zeros
            if (n1 as usize) < (threshold as usize) || (n2 as usize) < (threshold as usize) {
                // already zeros
            } else {
                let norm = (n1 as f64) * (n2 as f64 / window_area);


                let norm = (n1 as f64) * (n2 as f64 / window_area);

                let mut c = fill[pair];
                k_obs[pair][0] = c / norm;

                for k in 0..eff_bins {
                    let val = bins[pair * eff_bins + k];
                    c += val;
                    if k+1 < n_bins {
                        k_obs[pair][k+1] = c / norm;
                    }
                }
            }
        }
    }

    // --- Build Python dict ---
    let out = PyDict::new(py);

    for i in 0..L {
        for j in 0..L {
            let pair = i*L + j;

            let n1 = counts[i] as f64;
            let n2 = counts[j] as f64;

            // Threshold/area gate: if invalid, leave zeros
            let k_theo = if (n1 as usize) < (threshold as usize) || (n2 as usize) < (threshold as usize) {
                    vec![0.0f64; n_bins]
                } else {
                    theoretical_k(&radii, new_max, n1 as f64, n2 as f64, window_area)
                };

            let key = format!("{}___{}", unique[i], unique[j]);

            let val = (
                numpy::PyArray1::from_vec(py, k_obs[pair].clone()),
                numpy::PyArray1::from_vec(py, k_theo),
                numpy::PyArray1::from_vec(py, perm_acc[pair].clone()),
            );

            out.set_item(key, val)?;
        }
    }

    Ok(out.into())
}

#[pymodule]
fn rust_spaceanova(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(k_all_at_once_optimized, m)?)?;
    Ok(())
}