// Note this file was generated by AI (Microsoft's Copilot) as part of attempting to port the python in palmettobug (for spaceANOVA) into Rust
// This includes porting the translations of R code (primarily spatstat) that has their own license information -- see the original spaceanova.py file inside
// PalmettoBUG and/or the Other_License_Details.txt file for information about those packages & their licenses


// AI debugging: lines of code I commented out are marked with a unique comment ID -->     //##
// search for this to find these lines for later fixing (if needed)

use numpy::{PyArray1, PyReadonlyArray1};
use pyo3::prelude::*;
use rayon::prelude::*;
use rand::prelude::*;
use rand_pcg::Pcg64Mcg;
use std::collections::HashMap;
use std::f64::consts::PI;

/// Numerical epsilon check (equivalent to numpy finfo eps logic in spirit).
#[inline]
fn is_small(x: f64) -> bool {
    x.abs() < f64::EPSILON
}

#[inline]
fn hang(d: f64, r: f64) -> f64 {
    if r > d && r > 0.0 {
        let v = (d / r).clamp(-1.0, 1.0);
        v.acos()
    } else {
        0.0
    }
}

/// Precomputed per-point geometry relative to the window for Ripley isotropic edge correction.
#[derive(Clone, Copy, Debug)]
struct PointGeom {
    d_left: f64,
    d_right: f64,
    d_up: f64,
    d_down: f64,
    corner: bool,
    ang_left_up: f64,
    ang_left_down: f64,
    ang_right_up: f64,
    ang_right_down: f64,
    ang_up_left: f64,
    ang_up_right: f64,
    ang_down_left: f64,
    ang_down_right: f64,
}

impl PointGeom {
    fn from_xy(x: f64, y: f64, xmin: f64, xmax: f64, ymin: f64, ymax: f64) -> Self {
        let d_left = x - xmin;
        let d_right = xmax - x;
        let d_up = y - ymin;
        let d_down = ymax - y;

        let corner = ((is_small(d_left) as i32)
            + (is_small(d_right) as i32)
            + (is_small(d_down) as i32)
            + (is_small(d_up) as i32))
            >= 2;

        let ang_left_up = d_up.atan2(d_left);
        let ang_left_down = d_down.atan2(d_left);
        let ang_right_up = d_up.atan2(d_right);
        let ang_right_down = d_down.atan2(d_right);
        let ang_up_left = d_left.atan2(d_up);
        let ang_up_right = d_right.atan2(d_up);
        let ang_down_left = d_left.atan2(d_down);
        let ang_down_right = d_right.atan2(d_down);

        Self {
            d_left,
            d_right,
            d_up,
            d_down,
            corner,
            ang_left_up,
            ang_left_down,
            ang_right_up,
            ang_right_down,
            ang_up_left,
            ang_up_right,
            ang_down_left,
            ang_down_right,
        }
    }

    #[inline]
    fn weight(&self, r: f64) -> f64 {
        // Four hangs depend on r
        let angle_left = hang(self.d_left, r);
        let angle_right = hang(self.d_right, r);
        let angle_down = hang(self.d_down, r);
        let angle_up = hang(self.d_up, r);

        // mins with static angles:
        let mini_left = angle_left.min(self.ang_left_up) + angle_left.min(self.ang_left_down);
        let mini_right = angle_right.min(self.ang_right_up) + angle_right.min(self.ang_right_down);
        let mini_down = angle_down.min(self.ang_down_left) + angle_down.min(self.ang_down_right);
        let mini_up = angle_up.min(self.ang_up_left) + angle_up.min(self.ang_up_right);

        let mut total = mini_left + mini_right + mini_down + mini_up;
        if self.corner {
            total += PI / 2.0;
        }

        // weight = 1 / (1 - total / (2π)), clamped to [1, 100]
        let denom = 1.0 - (total / (2.0 * PI));
        let mut w = if denom <= 0.0 { 100.0 } else { 1.0 / denom };
        if w < 1.0 {
            w = 1.0;
        } else if w > 100.0 {
            w = 100.0;
        }
        w
    }
}

#[derive(Clone, Debug)]
struct Edge {
    left: usize,
    right: usize,
    dist: f64,
    w: f64, // weight computed for 'left' point
}

/// Simple 2D grid hashing to get neighbors within new_max efficiently.
fn build_grid(
    x: &[f64],
    y: &[f64],
    xmin: f64,
    ymin: f64,
    cell: f64,
) -> HashMap<(i32, i32), Vec<usize>> {
    let mut grid: HashMap<(i32, i32), Vec<usize>> = HashMap::new();
    for (i, (&xi, &yi)) in x.iter().zip(y.iter()).enumerate() {
        let gx = ((xi - xmin) / cell).floor() as i32;
        let gy = ((yi - ymin) / cell).floor() as i32;
        grid.entry((gx, gy)).or_default().push(i);
    }
    grid
}

fn precompute_edges(
    x: &[f64],
    y: &[f64],
    geom: &[PointGeom],
    xmin: f64,
    xmax: f64,
    ymin: f64,
    ymax: f64,
    new_max: f64,
) -> Vec<Edge> {
    if new_max <= 0.0 {
        return Vec::new();
    }
    let cell = new_max.max(1e-9);
    let grid = build_grid(x, y, xmin, ymin, cell);
    let n = x.len();
    let new_max2 = new_max * new_max;

    // Parallel over all left points
    let chunks: Vec<Vec<Edge>> = (0..n)
        .into_par_iter()
        .map(|i| {
            let xi = x[i];
            let yi = y[i];
            let gx = ((xi - xmin) / cell).floor() as i32;
            let gy = ((yi - ymin) / cell).floor() as i32;
            let mut local: Vec<Edge> = Vec::new();

            for dx in -1..=1 {
                for dy in -1..=1 {
                    let key = (gx + dx, gy + dy);
                    if let Some(idx_list) = grid.get(&key) {
                        for &j in idx_list {
                            if j == i {
                                continue;
                            }
                            let dx = x[j] - xi;
                            let dy = y[j] - yi;
                            let d2 = dx * dx + dy * dy;
                            if d2 <= new_max2 && d2 > 0.0 {
                                let r = d2.sqrt();
                                let w = geom[i].weight(r);
                                local.push(Edge {
                                    left: i,
                                    right: j,
                                    dist: r,
                                    w,
                                });
                            }
                        }
                    }
                }
            }
            local
        })
        .collect();

    let mut edges: Vec<Edge> = Vec::new();
    edges.reserve(chunks.iter().map(|v| v.len()).sum());
    for mut v in chunks {
        edges.append(&mut v);
    }
    edges
}

/// Produce the radii vector and truncation bound.
/// Mirrors Python behavior: if diameter/2 < max_r, we truncate to the largest r < (diameter/2).
fn make_radii_with_truncation(min_r: usize, max_r: usize, step: usize, diameter: f64) -> (Vec<f64>, f64, bool) {
    let radii: Vec<f64> = (min_r..=max_r).step_by(step).map(|r| r as f64).collect();
    let bound = diameter / 2.0;
    if bound < (max_r as f64) {
        // find last r < bound
        if let Some(&last) = radii.iter().filter(|&&r| r < bound).last() {
            (radii, last, true)
        } else {
            // No radii less than bound, effective truncation removes all bins
            (radii, 0.0, true)
        }
    } else {
        (radii, max_r as f64, false)
    }
}

/// Build theoretical K as π r² with radii > new_max set to 0 (by making those radii 0).
fn theoretical_k(radii: &[f64], new_max: f64, n1: usize, n2: usize, window_area: f64) -> Vec<f64> {
    let scale = if window_area > 0.0 { (n1 as f64) * (n2 as f64) / window_area } else { 0.0 };
    radii.iter()
        .map(|&r| {
            if r <= new_max {
                std::f64::consts::PI * r * r * scale
            } else {
                0.0
            }
        })
        .collect()
}


/// Histogram+cumulate per Python's logic using bins as in numpy.histogram(range=(lo, hi), bins=...).
/// Returns K counts (unnormalized), length == radii.len().
fn k_from_edges_counts(
    edges: &[Edge],
    labels: &[i64],
    type1: i64,
    type2: i64,
    min_r: usize,
    max_r: usize,
    step: usize,
    radii: &[f64],
    new_max: f64,
    threshold: usize,
    window_area: f64,
) -> Vec<f64> {
    let n_bins = radii.len();
    if n_bins == 0 {
        return Vec::new();
    }

    // Counts per type
    let mut n1: usize = 0;
    let mut n2: usize = 0;
    for &lab in labels {
        if lab == type1 {
            n1 += 1;
        } else if lab == type2 {
            n2 += 1;
        }
    }
    if n1 < threshold || n2 < threshold || n1 == 0 || n2 == 0 {
        return vec![0.0; n_bins];
    }
    if !(window_area.is_finite()) || window_area <= 0.0 {
        return vec![0.0; n_bins];
    }

    // Effective last index (not strictly needed, but keeps parity with your intent)
    let mut effective_last_index: Option<usize> = None;
    for (idx, &r) in radii.iter().enumerate() {
        if r <= new_max {
            effective_last_index = Some(idx);
        } else {
            break;
        }
    }
    if effective_last_index.is_none() {
        // No usable bins under new_max
        return vec![0.0; n_bins];
    }

    let lo = min_r as f64;
    let hi = new_max; // right-exclusive

    // Number of histogram bins up to new_max
    let eff_bins = if min_r == 0 {
        ((new_max / (step as f64)).floor() as isize).max(0) as usize
    } else {
        ((((new_max - (min_r as f64)) / (step as f64)).floor()) as isize).max(0) as usize
    };

    // --- FIXED: Handle eff_bins == 0 correctly ---
    if eff_bins == 0 {
        let mut out = vec![0.0; n_bins];
        let mut sum = 0.0f64;
        for e in edges {
            if labels[e.left] == type1 && labels[e.right] == type2 {
                let d = e.dist;
                if d > 0.0 && d < hi {
                    sum += e.w;
                }
            }
        }
        let norm = (n1 as f64) * (n2 as f64 / window_area);
        if norm > 0.0 {
            out[0] = sum / norm;
        }
        return out;
    }

    // Weighted histogram over (lo, hi), bins=eff_bins (exclusive of hi)
    let mut bins = vec![0.0f64; eff_bins];
    let mut fill = 0.0f64; // weights for (0, min) when min > 0, else 0

    for e in edges {
        if labels[e.left] != type1 || labels[e.right] != type2 {
            continue;
        }
        let d = e.dist;
        if d <= 0.0 {
            continue;
        }
        if d < lo {
            fill += e.w;
        } else if d < hi {
            let k = ((d - lo) / (step as f64)).floor() as isize;
            if k >= 0 && (k as usize) < eff_bins {
                bins[k as usize] += e.w;
            }
        }
    }

    // cumulative: K = [fill, fill + cumsum(bins)] then pad zeros to n_bins
    let mut cum = vec![0.0f64; eff_bins + 1];
    cum[0] = fill;
    for i in 0..eff_bins {
        cum[i + 1] = cum[i] + bins[i];
    }

    let norm = (n1 as f64) * (n2 as f64 / window_area);
    if norm > 0.0 {
        for v in &mut cum {
            *v /= norm;
        }
    } else {
        // degenerate; leave zeros
        for v in &mut cum {
            *v = 0.0;
        }
    }

    let mut out = vec![0.0f64; n_bins];
    let upto = (eff_bins).min(n_bins.saturating_sub(1));
    for i in 0..=upto {
        out[i] = cum[i];
    }
    out
}


#[pyfunction]
fn k_cross_homogeneous<'py>(
    py: Python<'py>,
    x: PyReadonlyArray1<f64>,
    y: PyReadonlyArray1<f64>,
    labels: PyReadonlyArray1<i64>,  // integer-encoded labels
    type1_code: i64,
    type2_code: i64,
    r_min: usize,
    r_max: usize,
    r_step: usize,
    threshold: usize,
    permutations: usize,
    perm_seed: u64,
) -> PyResult<(&'py PyArray1<f64>, &'py PyArray1<f64>, &'py PyArray1<f64>)> {
    let x = x.as_slice()?;
    let y = y.as_slice()?;
    let labels = labels.as_slice()?;

    
    let mut n1: usize = 0;
    let mut n2: usize = 0;
    for &lab in labels {
        if lab == type1_code {
            n1 += 1;
        } else if lab == type2_code {
            n2 += 1;
        }
    }

    if x.len() != y.len() || x.len() != labels.len() {
        return Err(PyErr::new::<pyo3::exceptions::PyValueError, _>(
            "x, y, labels must have the same length",
        ));
    }

    // Compute window & diameter
    let (xmin, xmax) = match (x.iter().cloned().fold(f64::INFINITY, f64::min),
                              x.iter().cloned().fold(f64::NEG_INFINITY, f64::max)) {
        (a, b) if a.is_finite() && b.is_finite() => (a, b),
        _ => (0.0, 0.0),
    };
    let (ymin, ymax) = match (y.iter().cloned().fold(f64::INFINITY, f64::min),
                              y.iter().cloned().fold(f64::NEG_INFINITY, f64::max)) {
        (a, b) if a.is_finite() && b.is_finite() => (a, b),
        _ => (0.0, 0.0),
    };
    let dx = xmax - xmin;
    let dy = ymax - ymin;
    let diameter = (dx * dx + dy * dy).sqrt();
    let window_area = (dx.max(0.0)) * (dy.max(0.0));

    // Radii and truncation bound
    let (radii, new_max, _truncated) = make_radii_with_truncation(r_min, r_max, r_step, diameter);
    let k_theo_vec = theoretical_k(&radii, n1, n2, new_max);

    // Precompute point geometry for edge weights
    let geom: Vec<PointGeom> = x
        .iter()
        .zip(y.iter())
        .map(|(&xi, &yi)| PointGeom::from_xy(xi, yi, xmin, xmax, ymin, ymax))
        .collect();

    // Build edges once (for all points; we need both directions because weights differ by origin)
    let edges = py.allow_threads(|| precompute_edges(x, y, &geom, xmin, xmax, ymin, ymax, new_max));

    // Compute K for current labeling
    let k_calc = py.allow_threads(|| {
        k_from_edges_counts(
            &edges,
            labels,
            type1_code,
            type2_code,
            r_min,
            r_max,
            r_step,
            &radii,
            new_max,
            threshold,
            window_area,
        )
    });

    // Permutation average if requested
    let k_perm_avg = if permutations == 0 {
        vec![0.0f64; radii.len()]
    } else {
        py.allow_threads(|| {
            let mut rng = Pcg64Mcg::seed_from_u64(perm_seed);
            // We'll average normalized K for each permutation.
            let mut acc = vec![0.0f64; radii.len()];
            let mut labels_perm: Vec<i64> = labels.to_vec();

            for _ in 0..permutations {
                labels_perm.shuffle(&mut rng);
                let k_perm = k_from_edges_counts(
                    &edges,
                    &labels_perm,
                    type1_code,
                    type2_code,
                    r_min,
                    r_max,
                    r_step,
                    &radii,
                    new_max,
                    threshold,
                    window_area,
                );
                debug_assert_eq!(k_perm.len(), acc.len());
                for (a, v) in acc.iter_mut().zip(k_perm.into_iter()) {
                    *a += v;
                }
            }
            for v in &mut acc {
                *v /= permutations as f64;
            }
            acc
        })
    };

    // Convert to numpy
    let k_calc_py = PyArray1::from_vec(py, k_calc);
    let k_theo_py = PyArray1::from_vec(py, k_theo_vec);
    let k_perm_py = PyArray1::from_vec(py, k_perm_avg);

    Ok((k_calc_py, k_theo_py, k_perm_py))
}

#[pymodule]
fn rust_spaceanova(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(k_cross_homogeneous, m)?)?;
    Ok(())
}