## This file was generated by AI (Microsoft's Copilot), then manually edited, as part of attempting to port the python in palmettobug (for spaceANOVA) into Rust
## This includes porting the translations of R code (primarily spaceanova) that has their own license information -- see the original spaceanova.py file inside
## PalmettoBUG and/or the Other_License_Details.txt file for information about those packages & their licenses

# palmettobug/_rust_k.py
import numpy as np

try:
    from ._native import k_cross_homogeneous as _k_cross_native
    _RUST_OK = True
except Exception:
    _RUST_OK = False

def has_rust() -> bool:
    return _RUST_OK

def _encode_labels(labels: np.ndarray, type1, type2) -> tuple[np.ndarray, int, int]:
    """
    Map arbitrary labels (str/int/object) to contiguous int codes for Rust.
    Returns (codes, type1_code, type2_code).
    """
    uniq, inv = np.unique(labels, return_inverse=True)
    # type1/type2 might not be present; handle gracefully
    try:
        t1_code = int(np.where(uniq == type1)[0][0])
    except IndexError:
        t1_code = -1
    try:
        t2_code = int(np.where(uniq == type2)[0][0])
    except IndexError:
        t2_code = -1
    return inv.astype(np.int64), t1_code, t2_code

def k_cross_homogeneous_py(
    x: np.ndarray,
    y: np.ndarray,
    labels: np.ndarray,
    type1,
    type2,
    r_min: int,
    r_max: int,
    r_step: int,
    threshold: int,
    permutations: int = 0,
    perm_seed: int = 42,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Python-friendly wrapper around the Rust kernel.
    Returns (K_calc, K_theoretical, K_perm_avg).
    If permutations == 0, K_perm_avg is all zeros.
    """
    if not _RUST_OK:
        raise RuntimeError("Rust extension not available")

    x = np.asarray(x, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)
    labels_arr = np.asarray(labels)
    codes, t1_code, t2_code = _encode_labels(labels_arr, type1, type2)

    if t1_code < 0 or t2_code < 0:
        # No valid points for one of the classes; return zeros of the right length
        radii_len = int((r_max - r_min) / r_step) + 1
        zeros = np.zeros(radii_len, dtype=np.float64)
        theo = zeros.copy()
        return zeros, theo, zeros

    K, K_theo, K_perm = _k_cross_native(
        x, y, codes,
        int(t1_code), int(t2_code),
        int(r_min), int(r_max), int(r_step),
        int(threshold),
        int(permutations), int(perm_seed),
    )
    # Ensure contiguous float64 arrays
    return np.array(K, dtype=np.float64), np.array(K_theo, dtype=np.float64), np.array(K_perm, dtype=np.float64)