## This file was generated by AI (Microsoft's Copilot), then manually edited, as part of attempting to port the python in palmettobug (for spaceANOVA) into Rust
## This includes porting the translations of R code (primarily spaceanova) that has their own license information -- see the original spaceanova.py file inside
## PalmettoBUG and/or the Other_License_Details.txt file for information about those packages & their licenses

# palmettobug/_rust_k.py
import numpy as np

try:
    from .rust_spaceanova import k_cross_homogeneous as _k_cross_native
    _RUST_OK = True
except Exception as e:
    print(e)
    _RUST_OK = False

def has_rust() -> bool:
    return _RUST_OK

def k_cross_homogeneous_py(
    x: np.ndarray,
    y: np.ndarray,
    labels: np.ndarray,
    type1,
    type2,
    r_min: int,
    r_max: int,
    r_step: int,
    threshold: int,
    permutations: int = 0,
    perm_seed: int = 42,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Python-friendly wrapper around the Rust kernel.
    Returns (K_calc, K_theoretical, K_perm_avg).
    If permutations == 0, K_perm_avg is all zeros.
    """
    if not _RUST_OK:
        raise RuntimeError("Rust extension not available")

    x = np.asarray(x, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)
    labels_arr = np.asarray(labels)


    K, K_theo, K_perm = _k_cross_native(
        x, y, codes,
        int(t1_code), int(t2_code),
        int(r_min), int(r_max), int(r_step),
        int(threshold),
        int(permutations), int(perm_seed),
    )
    # Ensure contiguous float64 arrays
    return np.array(K, dtype=np.float64), np.array(K_theo, dtype=np.float64), np.array(K_perm, dtype=np.float64)