// This code was generated by AI (Microsoft CoPilot), and then (likely or planned to be) edited 

use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyModule};

use numpy::{
    PyArray1, PyArray2, PyArray3, PyReadonlyArray1, PyReadonlyArray2, PyReadonlyArray3, ToPyArray,
};

use rust_spaceanova as sa;
use rust_sup_classifier as clf;

// ---- Helpers to check contiguity and convert arrays ----

// Check C-contiguity for (H, W) float32 arrays.
fn ensure_c_contiguous2(a: &PyReadonlyArray2<f32>) -> PyResult<()> {
    // Standard layout is a good proxy for C-order here.
    if !a.as_array().is_standard_layout() {
        return Err(PyValueError::new_err(
            "Expected a C-contiguous float32 array shaped (H, W). \
             Consider calling np.ascontiguousarray(x, dtype=np.float32).",
        ));
    }
    Ok(())
}

// Check C-contiguity for (C, H, W) float32 arrays.
fn ensure_c_contiguous3(a: &PyReadonlyArray3<f32>) -> PyResult<()> {
    if !a.as_array().is_standard_layout() {
        return Err(PyValueError::new_err(
            "Expected a C-contiguous float32 array shaped (C, H, W). \
             Consider calling np.ascontiguousarray(x, dtype=np.float32).",
        ));
    }
    Ok(())
}

// (H, W) -> Vec<Vec<f32>>
fn array2_to_vec2(arr: &PyReadonlyArray2<f32>) -> PyResult<Vec<Vec<f32>>> {
    // We don't require contiguity here; we convert safely via ndarray rows.
    let view = arr.as_array();
    let (h, _w) = view.dim();
    let mut out = Vec::with_capacity(h);
    for row in view.rows() {
        out.push(row.to_vec());
    }
    Ok(out)
}

// (C, H, W) -> Vec<Vec<Vec<f32>>>
fn array3_to_vec3(arr: &PyReadonlyArray3<f32>) -> PyResult<Vec<Vec<Vec<f32>>>> {
    let v = arr.as_array();
    let (c, h, w) = v.dim();
    let mut out = vec![vec![vec![0.0f32; w]; h]; c];
    for ci in 0..c {
        for yi in 0..h {
            for xi in 0..w {
                out[ci][yi][xi] = v[(ci, yi, xi)];
            }
        }
    }
    Ok(out)
}

// Vec<Vec<Vec<f32>>> -> (A, B, C) PyArray3 following the nesting order
fn vec3_to_py<'py>(py: Python<'py>, v: Vec<Vec<Vec<f32>>>) -> &'py PyArray3<f32> {
    let a = v.len();
    let b = v[0].len();
    let c = v[0][0].len();
    let flat: Vec<f32> = v.into_iter().flatten().flatten().collect();
    PyArray3::from_shape_vec(py, (a, b, c), flat).expect("Failed to construct PyArray3")
}

fn to_py_err<E: std::fmt::Display>(e: E) -> pyo3::PyErr {
    pyo3::exceptions::PyRuntimeError::new_err(e.to_string())
}


#[pyfunction]
fn k_all_at_once_optimized<'py>(
    py: Python<'py>,
    x: numpy::PyReadonlyArray1<f64>,
    y: numpy::PyReadonlyArray1<f64>,
    labels: Vec<String>,
    r_min: usize,
    r_max: usize,
    r_step: usize,
    threshold: usize,
    permutations: usize,
    perm_seed: u64,
) -> PyResult<Py<PyDict>> {
    // NumPy -> Rust
    let x = x.as_slice()?;
    let y = y.as_slice()?;

    // Call pure Rust
    let out_map = sa::k_all_at_once_optimized(
        x, y, &labels, r_min, r_max, r_step, threshold, permutations, perm_seed,
    ).map_err(to_py_err)?;

    // Rust map -> Python dict
    let dict = PyDict::new_bound(py);
    for (key, triple) in out_map {
        let k_obs   = PyArray1::from_vec(py, triple.k_obs);
        let k_theo  = PyArray1::from_vec(py, triple.k_theo);
        let permacc = PyArray1::from_vec(py, triple.perm_acc);

        // Tuple of NumPy arrays, just like your original API
        dict.set_item(key, (k_obs, k_theo, permacc))?;
    }

    Ok(dict.into())
}

#[pyfunction]
fn all_features_together_rust<'py>(
    py: Python<'py>,
    x: PyReadonlyArray3<f32>,     // Expect [C, H, W]
    channel_list: Vec<usize>,
    feature_list: Vec<String>,
    sigmas: Vec<f32>,
) -> PyResult<&'py PyArray3<f32>> {
    // Convert the 3D numpy array to nested Vec<Vec<Vec<f32>>> expected by the sub-library.
    // We accept non-contiguous inputs by copying when necessary.

    let view = x.as_array();
    let (c, h, w) = match view.dim() {
        (c, h, w) => (c, h, w),
    };

    // Build nested Vec in [C][H][W] order
    // If input is standard-layout, we could flatten once and split, but this path is simple and safe.
    let mut image_vec: Vec<Vec<Vec<f32>>> = Vec::with_capacity(c);
    for ci in 0..c {
        let mut ch: Vec<Vec<f32>> = Vec::with_capacity(h);
        for yi in 0..h {
            // row slice at [ci, yi, :]
            let mut row: Vec<f32> = Vec::with_capacity(w);
            for xi in 0..w {
                row.push(view[(ci, yi, xi)]);
            }
            ch.push(row);
        }
        image_vec.push(ch);
    }

    // Call the sub-library function with slices to avoid copying lists
    let layers: Vec<Vec<Vec<f32>>> =
        clf::all_features_together(&image_vec, &channel_list, &feature_list, &sigmas);

    // Convert Vec<Vec<Vec<f32>>> -> PyArray3<f32>
    if layers.is_empty() {
        // If no features produced, return an empty (0, h, w) array.
        let empty: Vec<f32> = Vec::new();
        let out = PyArray3::<f32>::from_shape_vec(py, (0, h, w), empty)
            .map_err(|_| PyValueError::new_err("Failed to construct empty output array"))?;
        return Ok(out);
    }

    // Validate layer shapes (defensive, but useful)
    for (i, layer) in layers.iter().enumerate() {
        if layer.len() != h || (!layer.is_empty() && layer[0].len() != w) {
            return Err(PyValueError::new_err(format!(
                "Feature layer {} has inconsistent shape; expected {}x{}, got {}x{}",
                i,
                h,
                w,
                layer.len(),
                if layer.is_empty() { 0 } else { layer[0].len() }
            )));
        }
    }

    let l = layers.len(); // number of layers
    // Flatten in [L][H][W] order
    let mut flat = Vec::with_capacity(l * h * w);
    for layer in layers {
        for row in layer {
            flat.extend_from_slice(&row);
        }
    }

    let out = PyArray3::<f32>::from_shape_vec(py, (l, h, w), flat)
        .map_err(|e| PyValueError::new_err(format!("Failed to construct output: {}", e)))?;
    Ok(out)
}


#[pyfunction]
fn make_features_rust<'py>(
    py: Python<'py>,
    x: PyReadonlyArray2<f32>,       // single-channel image [H, W]
    feature_list: &Vec<String>,
    sigma: f32,                     // single sigma
) -> PyResult<&'py numpy::PyArray3<f32>> {

    // Convert 2D ndarray view -> Vec<Vec<f32>> (works for non-contiguous too)
    let view = x.as_array();
    let (h, w) = view.dim();

    let mut image_vec: Vec<Vec<f32>> = Vec::with_capacity(h);
    for yi in 0..h {
        // copy row into Vec<f32>
        let mut row: Vec<f32> = Vec::with_capacity(w);
        for xi in 0..w {
            row.push(view[(yi, xi)]);
        }
        image_vec.push(row);
    }

    // Call the sub-library: returns Vec<Vec<Vec<f32>>> = [L][H][W]
    let layers = rust_sup_classifier::rust_make_features_single_channel(
        &image_vec,
        feature_list,
        sigma,
    );

    // Convert Vec<Vec<Vec<f32>>> -> PyArray3<f32> with shape (L, H, W)
    let l = layers.len();

    if l == 0 {
        // Return empty (0, H, W)
        let empty: Vec<f32> = Vec::new();
        let out = PyArray3::<f32>::from_shape_vec(py, (0, h, w), empty)
            .map_err(|_| PyValueError::new_err("Failed to construct empty output array"))?;
        return Ok(out);
    }

    // Defensive shape checks
    for (i, layer) in layers.iter().enumerate() {
        if layer.len() != h || (!layer.is_empty() && layer[0].len() != w) {
            return Err(PyValueError::new_err(format!(
                "Feature layer {} shape mismatch: expected {}x{}, got {}x{}",
                i,
                h,
                w,
                layer.len(),
                if layer.is_empty() { 0 } else { layer[0].len() }
            )));
        }
    }

    // Flatten in [L][H][W] order
    let mut flat = Vec::with_capacity(l * h * w);
    for layer in layers {
        for row in layer {
            flat.extend_from_slice(&row);
        }
    }

    let out = PyArray3::<f32>::from_shape_vec(py, (l, h, w), flat)
        .map_err(|e| PyValueError::new_err(format!("Failed to construct output: {}", e)))?;
    Ok(out)
}

#[pymodule]
fn _native(py: Python, m: &PyModule) -> PyResult<()> {
    // palmettobug.rust_spaceanova
    let sa_mod = PyModule::new(py, "rust_spaceanova")?;
    sa_mod.add_function(pyo3::wrap_pyfunction!(k_all_at_once_optimized, sa_mod)?)?;
    m.add_submodule(sa_mod)?;

    // palmettobug.rust_sup_classifier
    let clf_mod = PyModule::new(py, "rust_sup_classifier")?;
    clf_mod.add_function(pyo3::wrap_pyfunction!(
        all_features_together_rust,
        clf_mod
    )?)?;
    clf_mod.add_function(pyo3::wrap_pyfunction!(make_features_rust, clf_mod)?)?;
    m.add_submodule(clf_mod)?;

    Ok(())
}