// This code was generated by AI (Microsoft CoPilot), and then (likely or planned to be) edited 



use pyo3::prelude::*;
use pyo3::types::PyDict;
use numpy::{PyReadonlyArray1, PyReadonlyArray2, PyArray2, ToPyArray};

use rust_spaceanova as sa;
use rust_sup_classifier as clf;


// ---- Helpers to check contiguity quickly ----
fn ensure_c_contiguous2<'py>(py: Python<'py>, a: &PyArray2<f32>) -> PyResult<()> {
    if !a.is_c_contiguous() {
        return Err(PyValueError::new_err("Expected a C-contiguous float32 array (H, W). Consider calling np.ascontiguousarray(x, dtype=np.float32)."));
    }
    Ok(())
}
fn ensure_c_contiguous3<'py>(py: Python<'py>, a: &PyArray3<f32>) -> PyResult<()> {
    if !a.is_c_contiguous() {
        return Err(PyValueError::new_err("Expected a C-contiguous float32 array (C, H, W). Consider calling np.ascontiguousarray(x, dtype=np.float32)."));
    }
    Ok(())
}

// (H, W) -> Vec<Vec<f32>>
fn array2_to_vec2<'py>(py: Python<'py>, arr: &PyArray2<f32>) -> PyResult<Vec<Vec<f32>>> {
    ensure_c_contiguous2(py, arr)?;
    let (h, w) = arr.dim();
    let slice = unsafe { arr.as_slice().unwrap() };
    Ok(slice.chunks(w).map(|row| row.to_vec()).collect())
}

// (C, H, W) -> Vec<Vec<Vec<f32>>>
fn array3_to_vec3<'py>(py: Python<'py>, arr: &PyArray3<f32>) -> PyResult<Vec<Vec<Vec<f32>>>> {
    ensure_c_contiguous3(py, arr)?;
    let (c, h, w) = arr.dim();
    let slice = unsafe { arr.as_slice().unwrap() };

    let mut out = vec![vec![vec![0.0; w]; h]; c];
    let mut idx = 0;
    for ci in 0..c {
        for yi in 0..h {
            for xi in 0..w {
                out[ci][yi][xi] = slice[idx];
                idx += 1;
            }
        }
    }
    Ok(out)
}

// Vec<Vec<Vec<f32>>> -> (A, B, C) following the nesting order
fn vec3_to_py<'py>(py: Python<'py>, v: Vec<Vec<Vec<f32>>>) -> &'py PyArray3<f32> {
    let a = v.len();
    let b = v[0].len();
    let c = v[0][0].len();
    let flat: Vec<f32> = v.into_iter().flatten().flatten().collect();
    PyArray3::from_shape_vec(py, (a, b, c), flat).expect("Failed to construct PyArray3")
}

fn to_py_err<E: std::fmt::Display>(e: E) -> pyo3::PyErr {
    pyo3::exceptions::PyRuntimeError::new_err(e.to_string())
}


#[pyfunction]
fn k_all_at_once_optimized<'py>(
    py: Python<'py>,
    x: numpy::PyReadonlyArray1<f64>,
    y: numpy::PyReadonlyArray1<f64>,
    labels: Vec<String>,
    r_min: usize,
    r_max: usize,
    r_step: usize,
    threshold: usize,
    permutations: usize,
    perm_seed: u64,
) -> PyResult<Py<PyDict>> {
    // NumPy -> Rust
    let x = x.as_slice()?;
    let y = y.as_slice()?;

    // Call pure Rust
    let out_map = sa::k_all_at_once_optimized_impl(
        x, y, &labels, r_min, r_max, r_step, threshold, permutations, perm_seed,
    ).map_err(to_py_err)?;

    // Rust map -> Python dict
    let dict = PyDict::new_bound(py);
    for (key, triple) in out_map {
        let k_obs   = PyArray1::from_vec(py, triple.k_obs);
        let k_theo  = PyArray1::from_vec(py, triple.k_theo);
        let permacc = PyArray1::from_vec(py, triple.perm_acc);

        // Tuple of NumPy arrays, just like your original API
        dict.set_item(key, (k_obs, k_theo, permacc))?;
    }

    Ok(dict.into())
}


#[pyfunction]
fn all_channels_features_together_py<'py>(
    py: Python<'py>,
    x: PyReadonlyArray2<f32>,
) -> PyResult<&'py PyArray2<f32>> {
    // Best practice: work with ndarray view for zero-copy
    let x_view = x.as_array(); // ndarray::ArrayView2<'_, f32>

    // Call pure Rust impl (return type assumed ndarray::Array2<f32>)
    let feats = clf::all_channels_features_together_impl(x_view).map_err(to_py_err)?;

    Ok(feats.to_pyarray(py))
}

#[pyfunction]
fn make_features_py<'py>(
    py: Python<'py>,
    x: PyReadonlyArray2<f32>,
) -> PyResult<&'py PyArray2<f32>> {
    let x_view = x.as_array();
    let out = clf::make_features_impl(x_view).map_err(to_py_err)?;
    Ok(out.to_pyarray(py))
}

#[pymodule]
fn _native(py: Python, m: &PyModule) -> PyResult<()> {
    // palmettobug.rust_spaceanova
    let sa_mod = PyModule::new(py, "rust_spaceanova")?;
    sa_mod.add_function(pyo3::wrap_pyfunction!(k_all_at_once_optimized, sa_mod)?)?;
    m.add_submodule(sa_mod)?;

    // palmettobug.rust_sup_classifier
    let clf_mod = PyModule::new(py, "rust_sup_classifier")?;
    clf_mod.add_function(pyo3::wrap_pyfunction!(all_channels_features_together_py, clf_mod)?)?;
    clf_mod.add_function(pyo3::wrap_pyfunction!(make_features_py, clf_mod)?)?;
    m.add_submodule(clf_mod)?;

    Ok(())
}