// This code was generated by AI (Microsoft CoPilot), and then (likely or planned to be) edited both  maually and by AI assistance

use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyModule};
use pyo3::wrap_pyfunction;

use numpy::{PyArray1, PyArray2, PyArray3, PyReadonlyArray1, PyReadonlyArray2, PyReadonlyArray3};

use ndarray::{Array2, Array3, Axis};

use rust_spaceanova as sa;
use rust_sup_classifier as clf;
use rust_masks as rm;

// ------------------------- Error helper -------------------------

fn to_py_err<E: std::fmt::Display>(e: E) -> PyErr {
    PyValueError::new_err(e.to_string())
}

// ------------------------- Contiguity helpers -------------------------

#[inline]
fn ensure_c_contiguous2(a: &PyReadonlyArray2<f32>) -> PyResult<()> {
    if !a.as_array().is_standard_layout() {
        return Err(PyValueError::new_err(
            "Expected a C-contiguous float32 array shaped (H, W). \
             Consider calling np.ascontiguousarray(x, dtype=np.float32).",
        ));
    }
    Ok(())
}

#[inline]
fn ensure_c_contiguous3_f32(a: &PyReadonlyArray3<f32>) -> PyResult<()> {
    if !a.as_array().is_standard_layout() {
        return Err(PyValueError::new_err(
            "Expected a C-contiguous float32 array shaped (C, H, W). \
             Consider calling np.ascontiguousarray(x, dtype=np.float32).",
        ));
    }
    Ok(())
}

// ------------------------- Converters (ndarray-powered) -------------------------

// (H, W) -> Vec<Vec<f32>>
#[inline]
fn array2_to_vec2_f32(a: &PyReadonlyArray2<f32>) -> PyResult<Vec<Vec<f32>>> {
    let view = a.as_array();
    let mut out = Vec::with_capacity(view.len_of(Axis(0)));
    for row in view.rows() {
        out.push(row.to_vec());
    }
    Ok(out)
}

// Generic (C, H, W) -> Vec<Vec<Vec<T>>> for T: Clone
#[inline]
fn array3_to_vec3<T: Clone>(a: &PyReadonlyArray3<T>) -> PyResult<Vec<Vec<Vec<T>>>> where T: numpy::Element {
    let v = a.as_array();
    let c = v.len_of(Axis(0));
    let h = v.len_of(Axis(1));
    let mut out = Vec::with_capacity(c);
    for plane in v.axis_iter(Axis(0)) {
        let mut rows = Vec::with_capacity(h);
        for row in plane.axis_iter(Axis(0)) {
            rows.push(row.to_vec());
        }
        out.push(rows);
    }
    Ok(out)
}

// Vec<Vec<Vec<f32>>> -> PyArray3<f32> without unsafe copies.
// Uses ndarray::Array3 + numpy::PyArray::from_owned_array_bound.
#[inline]
fn vec3_to_pyarray3_f32<'py>(
    py: Python<'py>,
    v: Vec<Vec<Vec<f32>>>,
) -> PyResult<Bound<'py, PyArray3<f32>>> {
    let a = v.len();
    let b = v.first().map(|x| x.len()).unwrap_or(0);
    let c = v.first().and_then(|x| x.first().map(|y| y.len())).unwrap_or(0);

    // Validate rectangular (guards against ragged inputs)
    if a > 0 && b > 0 {
        for (i, plane) in v.iter().enumerate() {
            if plane.len() != b {
                return Err(PyValueError::new_err(format!(
                    "ragged dimension at v[{i}] has len {} != {b}",
                    plane.len()
                )));
            }
            for (j, row) in plane.iter().enumerate() {
                if row.len() != c {
                    return Err(PyValueError::new_err(format!(
                        "ragged dimension at v[{i}][{j}] has len {} != {c}",
                        row.len()
                    )));
                }
            }
        }
    }

    // Flatten in C-order (plane -> rows -> row contents)
    let expected = a.saturating_mul(b).saturating_mul(c);
    let mut flat = Vec::with_capacity(expected);
    for plane in &v {
        for row in plane {
            flat.extend_from_slice(row);
        }
    }
    debug_assert_eq!(flat.len(), expected);

    // Build ndarray then hand it to numpy without unsafe memcopy
    let arr = Array3::from_shape_vec((a, b, c), flat).map_err(to_py_err)?;
    let out = PyArray3::from_owned_array_bound(py, arr);
    Ok(out)
}

// ------------------------- Py functions -------------------------

#[pyfunction]
fn k_all_at_once_optimized<'py>(
    py: Python<'py>,
    x: PyReadonlyArray1<f64>,
    y: PyReadonlyArray1<f64>,
    labels: Vec<String>,
    r_min: usize,
    r_max: usize,
    r_step: usize,
    threshold: usize,
    permutations: usize,
    perm_seed: u64,
) -> PyResult<Py<PyDict>> {
    // C-contiguous enforced by PyO3 when calling as_slice()
    let x = x.as_slice()?;
    let y = y.as_slice()?;

    let out_map = sa::k_all_at_once_optimized(
        x, y, &labels, r_min, r_max, r_step, threshold, permutations, perm_seed,
    )
    .map_err(to_py_err)?;

    let dict = PyDict::new_bound(py);
    for (key, triple) in out_map {
        let k_obs = PyArray1::from_vec_bound(py, triple.k_obs);
        let k_theo = PyArray1::from_vec_bound(py, triple.k_theo);
        let permacc = PyArray1::from_vec_bound(py, triple.perm_acc);
        dict.set_item(key, (k_obs, k_theo, permacc))?;
    }

    Ok(dict.unbind())
}

#[pyfunction]
fn all_features_together_rust<'py>(
    py: Python<'py>,
    // [C, H, W] float32, C-contiguous
    x: PyReadonlyArray3<f32>,
    channel_list: Vec<usize>,
    feature_list: Vec<String>,
    sigmas: Vec<f32>,
) -> PyResult<Bound<'py, PyArray3<f32>>> {
    // Enforce contiguity where we might depend on perf / stride assumptions
    ensure_c_contiguous3_f32(&x)?;
    let image_vec:   Vec<Vec<Vec<f32>>>   = array3_to_vec3(&x)?;

    // Call pure Rust lib (assumed: returns Vec<Vec<Vec<f32>>>)
    let layers = clf::all_features_together(&image_vec, channel_list.as_slice(), feature_list.as_slice(), sigmas.as_slice());

    // Empty -> (0, H, W)
    let (_c, h, w) = x.as_array().dim();
    if layers.is_empty() {
        let out = PyArray3::<f32>::zeros_bound(py, (0, h, w), false);
        return Ok(out);
    }

    // Validate layer shapes match (H, W)
    for (i, layer) in layers.iter().enumerate() {
        if layer.len() != h || (!layer.is_empty() && layer[0].len() != w) {
            return Err(PyValueError::new_err(format!(
                "Feature layer {i} has inconsistent shape; expected {h}x{w}, got {}x{}",
                layer.len(),
                if layer.is_empty() { 0 } else { layer[0].len() }
            )));
        }
    }

    // Pack results without unsafe
    vec3_to_pyarray3_f32(py, layers)
}

#[pyfunction]
fn make_features_rust<'py>(
    py: Python<'py>,
    // single-channel [H, W]
    x: PyReadonlyArray2<f32>,
    // string list
    feature_list: Vec<String>,
    // single sigma
    sigma: f32,
) -> PyResult<Bound<'py, PyArray3<f32>>> {
    ensure_c_contiguous2(&x)?;
    let image_vec: Vec<Vec<f32>> = array2_to_vec2_f32(&x)?;

    // Call pure Rust lib
    let layers = clf::rust_make_features_single_channel(&image_vec, feature_list.as_slice(), sigma);

    // Empty -> (0, H, W)
    let (h, w) = x.as_array().dim();
    if layers.is_empty() {
        let out = PyArray3::<f32>::zeros_bound(py, (0, h, w), false);
        return Ok(out);
    }

    // Validate shapes
    for (i, layer) in layers.iter().enumerate() {
        if layer.len() != h || (!layer.is_empty() && layer[0].len() != w) {
            return Err(PyValueError::new_err(format!(
                "Feature layer {i} shape mismatch: expected {h}x{w}, got {}x{}",
                layer.len(),
                if layer.is_empty() { 0 } else { layer[0].len() }
            )));
        }
    }

    // Pack results without unsafe
    vec3_to_pyarray3_f32(py, layers)
}


#[pyfunction]
fn get_gaussian_derivs <'py>(
    py: Python<'py>,
    sigma: f32,
) -> PyResult<(
    pyo3::Bound<'py, PyArray1<f32>>,
    pyo3::Bound<'py, PyArray1<f32>>,
    pyo3::Bound<'py, PyArray1<f32>>)> {
    let (g, dg, d2g) = clf::get_gaussian_derivs(sigma);

    // Construct NumPy arrays (1D)
    let g_arr  = PyArray1::from_vec_bound(py, g);
    let dg_arr = PyArray1::from_vec_bound(py, dg);
    let d2g_arr= PyArray1::from_vec_bound(py, d2g);

    Ok((g_arr, dg_arr, d2g_arr))
}


#[pyfunction]
fn mask_boolean<'py>(
    py: Python<'py>,
    mask1: PyReadonlyArray2<usize>,
    mask2: PyReadonlyArray2<usize>,
    kind: &str,
    object_threshold: usize,
    pixel_threshold: usize,
    re_order: bool
)  -> PyResult<pyo3::Bound<'py, PyArray2<usize>>>{
    let mask1: Vec<Vec<usize>> = array2_to_vec2_f32(&mask1)?;
    let mask2: Vec<Vec<usize>> = array2_to_vec2_f32(&mask2)?;
    
    let output_mask: Vec<Vec<usize>> = rm.mask_boolean_rust(&mask1_vec, &mask2_vec, kind,
        object_threshold, pixel_threshold, re_order);

    let rows = output_mask.len();
    let cols = if rows == 0 { 0 } else { output_mask[0].len() };
    // Flatten row-major
    let flat: Vec<usize> = output_mask.into_iter().flatten().collect();

    let out_array: Array2<usize> =
        Array2::from_shape_vec((rows, cols), flat)
            .expect("inconsistent row lengths in output");

    // Return as a NumPy array bound to `py`
    Ok(out_array.to_pyarray_bound(py))
}



#[pyfunction]
fn sep_filter_2d<'py>(
    py: Python<'py>,
    image: PyReadonlyArray2<'_, f32>,   // H x W
    kernel_x: PyReadonlyArray1<'_, f32>,// W-kernel
    kernel_y: PyReadonlyArray1<'_, f32>,// H-kernel
) -> PyResult<Py<PyArray2<f32>>> {
    // Convert inputs to Rust-owned containers (zero-copy views -> owned Vecs)
    let img2d = image.as_array();
    let img_vec: Vec<Vec<f32>> = img2d
        .rows()
        .into_iter()
        .map(|r| r.to_vec())
        .collect();

    let kx: Vec<f32> = kernel_x.as_slice()?.to_vec();
    let ky: Vec<f32> = kernel_y.as_slice()?.to_vec();

    // Call your Rust implementation (module path assumed)
    let out: Vec<Vec<f32>> = clf::sep_filter_2d(&img_vec, &kx, &ky);

    // Validate rectangular shape
    let h = out.len();
    let w = if h > 0 { out[0].len() } else { 0 };
    if !out.iter().all(|row| row.len() == w) {
        return Err(PyValueError::new_err(
            "sep_filter_2d returned a ragged Vec<Vec<f32>>; expected rectangular matrix",
        ));
    }

    // Convert Vec<Vec<f32>> -> ndarray::Array2 -> NumPy array
    let flat: Vec<f32> = out.into_iter().flatten().collect();
    let arr = Array2::from_shape_vec((h, w), flat)
        .map_err(|e| PyValueError::new_err(format!("shape error: {e}")))?;
    let py_arr: &PyArray2<f32> = PyArray2::from_owned_array(py, arr);

    Ok(py_arr.to_owned()) // Py<PyArray2<f32>>
}


#[pymodule]
fn _central(py: Python, m: &Bound<PyModule>) -> PyResult<()> {
    // palmettobug.rust_spaceanova
    let sa_mod = PyModule::new_bound(py, "rust_spaceanova")?;
    sa_mod.add_function(wrap_pyfunction!(k_all_at_once_optimized, &sa_mod)?)?;
    m.add_submodule(&sa_mod)?;

    // palmettobug.rust_masks
    let rm_mod = PyModule::new_bound(py, "rust_masks")?;
    rm_mod.add_function(wrap_pyfunction!(mask_boolean, &rm_mod)?)?;
    m.add_submodule(&rm_mod)?;

    // palmettobug.rust_sup_classifier
    let clf_mod = PyModule::new_bound(py, "rust_sup_classifier")?;
    clf_mod.add_function(wrap_pyfunction!(all_features_together_rust, &clf_mod)?)?;
    clf_mod.add_function(wrap_pyfunction!(make_features_rust, &clf_mod)?)?;
    clf_mod.add_function(wrap_pyfunction!(get_gaussian_derivs, &clf_mod)?)?;
    clf_mod.add_function(wrap_pyfunction!(sep_filter_2d, &clf_mod)?)?;
    m.add_submodule(&clf_mod)?;

    
    // Make `from palmettobug.rust_sup_classifier import ...` work:
    let sys = PyModule::import(py, "sys")?;
    sys.dict().set_item("palmettobug.rust_sup_classifier", &clf_mod)?;
    sys.dict().set_item("palmettobug.rust_spaceanova", &sa_mod)?;
    sys.dict().set_item("palmettobug.rust_masks", &rm_mod)?;

    Ok(())
}

