// This code was generated by Microsoft CoPilot AI (then modified). It is a port of the PalmettoBUG code in Pixel_Classification/Classifiers.py, which was in turn
// a translation of QuPath code from Java --> Python. QuPath is also GPL-3 licensed, see Other_License_Details.txt for more information and full copyright list

// 2D convolution and sobel filter functions were also generated by the AI specifically as replacements to opencv's functions used in the original palmettobug file
// However, no code from opencv (except the calls to the API from inside palmettobug) was copied into the AI prompt and the AI was specifically asked to not copy from opencv but to design its own functions
// 2D convolutions and sobel filters are common image analysis operations, so although intentionally matching the functionality of opencv including 'replicate' border-handling,
// as functionality is by itself non-copyrightable, the AI code here presumably should not be considered derived from opencv.
// In case any part of this file does rise to the level of derivation, the copyrights & top-level license (Apache 2.0) for opencv are included in 
// Other_License_Details.txt 


// --------------------------------------------------------------
//  Feature extraction module translated from Python to Rust
//  OpenCV-dependent functions are replaced with placeholders  --> inturn replaced with AI created convolution/sobel filters
//  The logic and data transformations match your Python code
// --------------------------------------------------------------

use std::f32::consts::PI;
use pyo3::prelude::*;
use pyo3::exceptions::*;
use numpy::{PyArray2, PyArray3, PyArray1};
use numpy::IntoPyArray;

//
// ========== Utility Conversion Helpers ==========
//

// ---- Helpers to check contiguity quickly ----
fn ensure_c_contiguous2<'py>(py: Python<'py>, a: &PyArray2<f32>) -> PyResult<()> {
    if !a.is_c_contiguous() {
        return Err(PyValueError::new_err("Expected a C-contiguous float32 array (H, W). Consider calling np.ascontiguousarray(x, dtype=np.float32)."));
    }
    Ok(())
}
fn ensure_c_contiguous3<'py>(py: Python<'py>, a: &PyArray3<f32>) -> PyResult<()> {
    if !a.is_c_contiguous() {
        return Err(PyValueError::new_err("Expected a C-contiguous float32 array (C, H, W). Consider calling np.ascontiguousarray(x, dtype=np.float32)."));
    }
    Ok(())
}

// (H, W) -> Vec<Vec<f32>>
fn array2_to_vec2<'py>(py: Python<'py>, arr: &PyArray2<f32>) -> PyResult<Vec<Vec<f32>>> {
    ensure_c_contiguous2(py, arr)?;
    let (h, w) = arr.dim();
    let slice = unsafe { arr.as_slice().unwrap() };
    Ok(slice.chunks(w).map(|row| row.to_vec()).collect())
}

// (C, H, W) -> Vec<Vec<Vec<f32>>>
fn array3_to_vec3<'py>(py: Python<'py>, arr: &PyArray3<f32>) -> PyResult<Vec<Vec<Vec<f32>>>> {
    ensure_c_contiguous3(py, arr)?;
    let (c, h, w) = arr.dim();
    let slice = unsafe { arr.as_slice().unwrap() };

    let mut out = vec![vec![vec![0.0; w]; h]; c];
    let mut idx = 0;
    for ci in 0..c {
        for yi in 0..h {
            for xi in 0..w {
                out[ci][yi][xi] = slice[idx];
                idx += 1;
            }
        }
    }
    Ok(out)
}

// Vec<Vec<f32>> -> (H, W)
fn vec2_to_py<'py>(py: Python<'py>, v: Vec<Vec<f32>>) -> &'py PyArray2<f32> {
    // This performs one allocation/copy internally; no need to flatten manually.
    PyArray2::from_vec2(py, &v).expect("unable to create PyArray2 from Vec<Vec<f32>>")
}

// Vec<Vec<Vec<f32>>> -> (A, B, C) following the nesting order
fn vec3_to_py<'py>(py: Python<'py>, v: Vec<Vec<Vec<f32>>>) -> &'py PyArray3<f32> {
    let a = v.len();
    let b = v[0].len();
    let c = v[0][0].len();
    let flat: Vec<f32> = v.into_iter().flatten().flatten().collect();
    PyArray3::from_shape_vec(py, (a, b, c), flat).expect("Failed to construct PyArray3")
}

/// Clamp `v` into the inclusive range [lo, hi].
#[inline]
fn clamp_usize(v: isize, lo: usize, hi: usize) -> usize {
    if v < lo as isize { lo } else if v > hi as isize { hi } else { v as usize }
}

#[inline]
fn zeros_like(like: &Vec<Vec<f32>>) -> Vec<Vec<f32>> {
    let h = like.len();
    let w = like[0].len();
    vec![vec![0.0; w]; h]
}

#[inline(always)]
fn build_replicate_index_map(size: usize, radius: usize) -> Vec<Vec<usize>> {
    let mut map = vec![vec![0usize; 2 * radius + 1]; size];

    for i in 0..size {
        for k in 0..(2 * radius + 1) {
            let idx = i as isize + k as isize - radius as isize;

            // Replicate border handling: identical results to clamp()
            map[i][k] = if idx < 0 {
                0
            } else if idx >= size as isize {
                size - 1
            } else {
                idx as usize
            };
        }
    }

    map
}


/// Minimal 2D convolution with **replicate** border handling (OpenCV borderType=1).
#[inline(always)]
pub fn conv2d_replicate(
    image: &Vec<Vec<f32>>,
    kernel: &Vec<Vec<f32>>,
) -> Vec<Vec<f32>> {
    let h = image.len();
    let w = image[0].len();

    let kh = kernel.len();
    let kw = kernel[0].len();

    let ry = kh / 2;
    let rx = kw / 2;

    // Precompute replicate-border indices:
    let idx_y = build_replicate_index_map(h, ry);
    let idx_x = build_replicate_index_map(w, rx);

    let mut out = vec![vec![0.0f32; w]; h];

    for y in 0..h {
        let out_row = &mut out[y];
        let idx_y_row = &idx_y[y];

        for x in 0..w {
            let idx_x_row = &idx_x[x];

            let mut acc = 0.0f32;

            // Completely branch-free:
            for ky in 0..kh {
                let yy = idx_y_row[ky];
                let row_img = &image[yy];
                let row_ker = &kernel[ky];

                for kx in 0..kw {
                    let xx = idx_x_row[kx];
                    acc += row_img[xx] * row_ker[kx];
                }
            }

            out_row[x] = acc;
        }
    }

    out
}

/// 1D horizontal pass: convolve each row with `kernel_x` (odd length), replicate borders.
#[inline(always)]
fn convolve_horizontal_replicate(
    image: &Vec<Vec<f32>>,
    kernel_x: &Vec<f32>,
) -> Vec<Vec<f32>> {
    let h = image.len();
    let w = image[0].len();
    let k = kernel_x.len();
    let r = k / 2;

    // Precompute replicate indices for x-axis
    let idx_x = build_replicate_index_map(w, r);

    let mut out = vec![vec![0.0f32; w]; h];

    for y in 0..h {
        let row = &image[y];
        let out_row = &mut out[y];

        for x in 0..w {
            let idx_row = &idx_x[x];
            let mut acc = 0.0f32;

            // branch-free & bounds-check-free
            for i in 0..k {
                acc += row[idx_row[i]] * kernel_x[i];
            }

            out_row[x] = acc;
        }
    }

    out
}

/// 1D vertical pass: convolve each column with `kernel_y` (odd length), replicate borders.
#[inline(always)]
fn convolve_vertical_replicate(
    image: &Vec<Vec<f32>>,
    kernel_y: &Vec<f32>,
) -> Vec<Vec<f32>> {
    let h = image.len();
    let w = image[0].len();
    let k = kernel_y.len();
    let r = k / 2;

    // Precompute replicate indices for y-axis
    let idx_y = build_replicate_index_map(h, r);

    let mut out = vec![vec![0.0f32; w]; h];

    for y in 0..h {
        let out_row = &mut out[y];
        let idx_row = &idx_y[y];

        for x in 0..w {
            let mut acc = 0.0f32;

            // branch-free & bounds-check-free
            for i in 0..k {
                acc += image[idx_row[i]][x] * kernel_y[i];
            }

            out_row[x] = acc;
        }
    }

    out
}

/// Minimal **separable** 2D filter with replicate borders; replacement for cv.sepFilter2D(image, kernelX, kernelY, borderType=1).
#[inline(always)]
pub fn sep_filter_2d(
    image: &Vec<Vec<f32>>,
    kernel_x: &Vec<f32>,
    kernel_y: &Vec<f32>,
) -> Vec<Vec<f32>> {
    let tmp = convolve_horizontal_replicate(image, kernel_x);
    convolve_vertical_replicate(&tmp, kernel_y)
}
}

/// 3×3 Sobel operator with replicate borders.
/// Returns (dx, dy, magnitude) as three H×W images.
/// - dx uses kernel Gx = [[-1,0,1], [-2,0,2], [-1,0,1]]
/// - dy uses kernel Gy = [[-1,-2,-1], [0,0,0], [1,2,1]]
pub fn sobel_3x3(image: &Vec<Vec<f32>>) -> (Vec<Vec<f32>>, Vec<Vec<f32>>, Vec<Vec<f32>>) {
    // Define Sobel kernels (row-major)
    let gx = vec![
        vec![-1.0,  0.0,  1.0],
        vec![-2.0,  0.0,  2.0],
        vec![-1.0,  0.0,  1.0],
    ];
    let gy = vec![
        vec![-1.0, -2.0, -1.0],
        vec![ 0.0,  0.0,  0.0],
        vec![ 1.0,  2.0,  1.0],
    ];

    let dx = conv2d_replicate(image, &gx);
    let dy = conv2d_replicate(image, &gy);

    // Gradient magnitude = sqrt(dx^2 + dy^2)
    let h = image.len();
    let w = image[0].len();
    let mut mag = vec![vec![0.0f32; w]; h];
    for y in 0..h {
        for x in 0..w {
            let vx = dx[y][x];
            let vy = dy[y][x];
            mag[y][x] = (vx * vx + vy * vy).sqrt();
        }
    }

    (dx, dy, mag)
}

// =============================================================
// Equivalent of _getGaussianDerivs()
// =============================================================
fn get_gaussian_derivs(sigma: f32) -> (Vec<f32>, Vec<f32>, Vec<f32>) {
    let length = (sigma * 8.0).floor() as usize + 1;
    let n = length / 2;

    let denom2 = 2.0 * sigma * sigma;

    // ---------------- kernel0 ----------------
    let denom0 = sigma * (2.0 * PI).sqrt();
    let mut kernel0 = vec![0.0f32; length];

    for i in 0..length {
        let pos = i as i32 - n as i32;
        let val = f32::exp(-(pos * pos) as f32 / denom2);
        kernel0[i] = val / denom0;
    }

    // ---------------- kernel1 ----------------
    let denom1 = sigma.powi(3) * (2.0 * PI).sqrt();
    let mut kernel1 = vec![0.0f32; length];

    for i in 0..length {
        let pos = i as i32 - n as i32;
        let val = -(pos as f32) * f32::exp(-(pos * pos) as f32 / denom2);
        kernel1[i] = val / denom1;
    }

    // ---------------- kernel2 ----------------
    let denom2kernel = sigma.powi(5) * (2.0 * PI).sqrt();
    let mut kernel2 = vec![0.0f32; length];

    for i in 0..length {
        let pos = i as i32 - n as i32;
        let val = -(sigma * sigma - (pos * pos) as f32)
            * f32::exp(-(pos * pos) as f32 / denom2);
        kernel2[i] = val / denom2kernel;
    }

    (kernel0, kernel1, kernel2)
}

// =============================================================
// Equivalent of _getMixedDerivs()
// =============================================================
fn get_mixed_derivs(
    image: &Vec<Vec<f32>>,
    kernel0: &Vec<f32>,
    kernel1: &Vec<f32>,
    kernel2: &Vec<f32>,
) -> (Vec<Vec<f32>>, Vec<Vec<f32>>, Vec<Vec<f32>>) 
{
    let dxy = sep_filter_2d(image, kernel1, kernel1);
    let dxx = sep_filter_2d(image, kernel2, kernel0);
    let dyy = sep_filter_2d(image, kernel0, kernel2);
    (dxx, dyy, dxy)
}

// =============================================================
// Equivalent of _getLaplacian()
// =============================================================
fn get_laplacian(
    dxx: &Vec<Vec<f32>>,
    dyy: &Vec<Vec<f32>>,
) -> Vec<Vec<f32>> 
{
    let mut out = zeros_like(dxx);
    for i in 0..dxx.len() {
        for j in 0..dxx[0].len() {
            out[i][j] = dxx[i][j] + dyy[i][j];
        }
    }
    out
}

// =============================================================
// Hessian eigenvalue computation
// =============================================================
fn get_hessian(
    dxx: &Vec<Vec<f32>>,
    dyy: &Vec<Vec<f32>>,
    dxy: &Vec<Vec<f32>>,
) -> (Vec<Vec<f32>>, Vec<Vec<f32>>, Vec<Vec<f32>>) 
{
    let h = dxx.len();
    let w = dxx[0].len();

    let mut hmin = zeros_like(dxx);
    let mut hmax = zeros_like(dxx);
    let mut det  = zeros_like(dxx);

    for i in 0..h {
        for j in 0..w {
            let a = dxx[i][j];
            let b = dxy[i][j];
            let d = dyy[i][j];

            let trace = a + d;
            let delta = (trace * trace - 4.0 * (a * d - b * b)).sqrt();

            let l1 = (trace + delta) / 2.0;
            let l2 = (trace - delta) / 2.0;

            hmin[i][j] = f32::min(l1, l2);
            hmax[i][j] = f32::max(l1, l2);
            det[i][j]  = a * d - b * b;
        }
    }

    (hmin, hmax, det)
}

// =============================================================
// Structure Tensor
// =============================================================
fn get_structure_tensor(
    image: &Vec<Vec<f32>>,
    kernel0: &Vec<f32>,
    compute_coherence: bool,
) -> (Vec<Vec<f32>>, Vec<Vec<f32>>, Vec<Vec<f32>>) 
{
    let (dx, dy, mag) = sobel_3x3(image);

    let mut dxx = zeros_like(image);
    let mut dyy = zeros_like(image);
    let mut dxy = zeros_like(image);

    for i in 0..image.len() {
        for j in 0..image[0].len() {
            dxx[i][j] = dx[i][j] * dx[i][j];
            dyy[i][j] = dy[i][j] * dy[i][j];
            dxy[i][j] = dx[i][j] * dy[i][j];
        }
    }

    let dxx_f = sep_filter_2d(&dxx, kernel0, kernel0);
    let dyy_f = sep_filter_2d(&dyy, kernel0, kernel0);
    let dxy_f = sep_filter_2d(&dxy, kernel0, kernel0);

    let (st_min, st_max, _) = get_hessian(&dxx_f, &dyy_f, &dxy_f);

    let mut coherence = zeros_like(&st_min);
    if compute_coherence {
        for i in 0..st_min.len() {
            for j in 0..st_min[0].len() {
                let num = st_max[i][j] - st_min[i][j];
                let den = st_max[i][j] + st_min[i][j];
                if den != 0.0 {
                    coherence[i][j] = (num / den).powi(2);
                } else {
                    coherence[i][j] = 0.0;
                }
            }
        }
    }

    (st_min, st_max, coherence)
}


#[inline]
fn get_weighted_stddev(image: &Vec<Vec<f32>>, k0: &Vec<f32>) -> Vec<Vec<f32>> {
    // E[x] via Gaussian smoothing
    let mean = sep_filter_2d(image, k0, k0);

    // E[x^2]
    let h = image.len();
    let w = image[0].len();
    let mut sq = vec![vec![0.0f32; w]; h];
    for y in 0..h {
        for x in 0..w {
            let v = image[y][x];
            sq[y][x] = v * v;
        }
    }
    let mean_sq = sep_filter_2d(&sq, k0, k0);

    // Var = E[x^2] - (E[x])^2; clamp to 0 to avoid tiny negatives
    let mut stddev = vec![vec![0.0f32; w]; h];
    for y in 0..h {
        for x in 0..w {
            let var = (mean_sq[y][x] - mean[y][x] * mean[y][x]).max(0.0);
            stddev[y][x] = var.sqrt();
        }
    }
    stddev
}


// Unified features calculator

fn rust_make_features_single_channel(
    image: &Vec<Vec<f32>>,
    feature_list: &Vec<String>,
    sigma: f32,
) -> Vec<Vec<Vec<f32>>> {
    let (k0, k1, k2) = get_gaussian_derivs(sigma);
    let (dxx, dyy, dxy) = get_mixed_derivs(image, &k0, &k1, &k2);

    let mut layers: Vec<Vec<Vec<f32>>> = Vec::with_capacity(feature_list.len());

    let mut hess_cached: Option<(Vec<Vec<f32>>, Vec<Vec<f32>>, Vec<Vec<f32>>)> = None;
    let mut struct_cached: Option<(Vec<Vec<f32>>, Vec<Vec<f32>>, Vec<Vec<f32>>)> = None;

    for feat in feature_list {
        match feat.as_str() {
            "GRAD_MAG" => {
                let (_, _, mag) = sobel_3x3(image);
                layers.push(mag);
            }
            "HESSIAN_DET" => {
                if hess_cached.is_none() {
                    hess_cached = Some(get_hessian(&dxx, &dyy, &dxy));
                }
                let (_, _, det) = hess_cached.as_ref().unwrap();
                layers.push(det.clone());
            }
            "HESSIAN_MAX" => {
                if hess_cached.is_none() {
                    hess_cached = Some(get_hessian(&dxx, &dyy, &dxy));
                }
                let (_, maxv, _) = hess_cached.as_ref().unwrap();
                layers.push(maxv.clone());
            }
            "HESSIAN_MIN" => {
                if hess_cached.is_none() {
                    hess_cached = Some(get_hessian(&dxx, &dyy, &dxy));
                }
                let (minv, _, _) = hess_cached.as_ref().unwrap();
                layers.push(minv.clone());
            }
            "LAPLACIAN" => {
                layers.push(get_laplacian(&dxx, &dyy));
            }
            "STRUCT_CO" => {
                let (_, _, co) = get_structure_tensor(image, &k0, true);
                layers.push(co);
            }
            "STRUCT_MAX" => {
                if struct_cached.is_none() {
                    struct_cached = Some(get_structure_tensor(image, &k0, false));
                }
                let (_, maxv, _) = struct_cached.as_ref().unwrap();
                layers.push(maxv.clone());
            }
            "STRUCT_MIN" => {
                if struct_cached.is_none() {
                    struct_cached = Some(get_structure_tensor(image, &k0, false));
                }
                let (minv, _, _) = struct_cached.as_ref().unwrap();
                layers.push(minv.clone());
            }
            "WGT_STDV" => {
                layers.push(get_weighted_stddev(image, &k0));
            }
            other => panic!("Unknown feature: {}", other),
        }
    }

    // layers: Vec<F>{H×W}; Python sees shape (F, H, W) via vec3_to_py
    layers
}


// ===============================================================
//   PYTHON MODULE DEFINITION (PyO3 entry point) & API
// ===============================================================

#[pymodule]
fn rust_features(_py: Python, m: &PyModule) -> PyResult<()> {

    m.add_function(wrap_pyfunction!(make_features_py, m)?)?;
    m.add_function(wrap_pyfunction!(all_channels_features_together_py, m)?)?;

    Ok(())
}

#[pyfunction]
fn make_features_py<'py>(
    py: Python<'py>,
    image: &PyArray2<f32>,
    feature_list: Vec<String>,
    sigma: f32,
) -> PyResult<&'py PyArray3<f32>> {
    let img_vec = array2_to_vec2(py, image)?;
    let out = rust_make_features_single_channel(&img_vec, &feature_list, sigma);
    Ok(vec3_to_py(py, out))
}

#[pyfunction]
fn all_channels_features_together_py<'py>(
    py: Python<'py>,
    image: &PyArray3<f32>,
    channels: Vec<usize>,
    features: Vec<String>,
    sigmas: Vec<f32>,
) -> PyResult<&'py PyArray3<f32>> {
    let img = array3_to_vec3(py, image)?;

    let details = crate::ClassifierDetails {
        channel_list: channels,
        features_list: features,
        sigma_list: sigmas,
    };

    let out = crate::all_channels_features_together(&img, &details);
    Ok(vec3_to_py(py, out))
}

