// This code was generated by Microsoft CoPilot AI (then modified). It is a port of the PalmettoBUG code in Pixel_Classification/Classifiers.py, which was in turn
// a translation of QuPath code from Java --> Python. QuPath is also GPL-3 licensed, see Other_License_Details.txt for more information and full copyright list

// 2D convolution and sobel filter functions were also generated by the AI specifically as replacements to opencv's functions used in the original palmettobug file
// However, no code from opencv (except the calls to the API from inside palmettobug) was copied into the AI prompt and the AI was specifically asked to not copy from opencv but to design its own functions
// 2D convolutions and sobel filters are common image analysis operations, so although intentionally matching the functionality of opencv including 'replicate' border-handling,
// as functionality is by itself non-copyrightable, the AI code here presumably should not be considered derived from opencv.
// In case any part of this file does rise to the level of derivation, the copyrights & top-level license (Apache 2.0) for opencv are included in 
// Other_License_Details.txt 


// --------------------------------------------------------------
//  Feature extraction module translated from Python to Rust
//  OpenCV-dependent functions are replaced with placeholders  --> inturn replaced with AI created convolution/sobel filters
//  The logic and data transformations match your Python code
// --------------------------------------------------------------

use std::f32::consts::PI;


#[inline]
fn zeros_like(like: &Vec<Vec<f32>>) -> Vec<Vec<f32>> {
    let h = like.len();
    let w = like[0].len();
    vec![vec![0.0; w]; h]
}

#[inline(always)]
fn build_replicate_index_map(size: usize, radius: usize) -> Vec<Vec<usize>> {
    let mut map = vec![vec![0usize; 2 * radius + 1]; size];

    for i in 0..size {
        for k in 0..(2 * radius + 1) {
            let idx = i as isize + k as isize - radius as isize;

            // Replicate border handling: identical results to clamp()
            map[i][k] = if idx < 0 {
                0
            } else if idx >= size as isize {
                size - 1
            } else {
                idx as usize
            };
        }
    }

    map
}


/// Minimal 2D convolution with **replicate** border handling (OpenCV borderType=1).
#[inline(always)]
pub fn conv2d_replicate(
    image: &Vec<Vec<f32>>,
    kernel: &Vec<Vec<f32>>,
) -> Vec<Vec<f32>> {
    let h = image.len();
    let w = image[0].len();

    let kh = kernel.len();
    let kw = kernel[0].len();

    let ry = kh / 2;
    let rx = kw / 2;

    // Precompute replicate-border indices:
    let idx_y = build_replicate_index_map(h, ry);
    let idx_x = build_replicate_index_map(w, rx);

    let mut out = vec![vec![0.0f32; w]; h];

    for y in 0..h {
        let out_row = &mut out[y];
        let idx_y_row = &idx_y[y];

        for x in 0..w {
            let idx_x_row = &idx_x[x];

            let mut acc = 0.0f32;

            // Completely branch-free:
            for ky in 0..kh {
                let yy = idx_y_row[ky];
                let row_img = &image[yy];
                let row_ker = &kernel[ky];

                for kx in 0..kw {
                    let xx = idx_x_row[kx];
                    acc += row_img[xx] * row_ker[kx];
                }
            }

            out_row[x] = acc;
        }
    }

    out
}

/// 1D horizontal pass: convolve each row with `kernel_x` (odd length), replicate borders.
#[inline(always)]
fn convolve_horizontal_replicate(
    image: &Vec<Vec<f32>>,
    kernel_x: &Vec<f32>,
) -> Vec<Vec<f32>> {
    let h = image.len();
    let w = image[0].len();
    let k = kernel_x.len();
    let r = k / 2;

    // Precompute replicate indices for x-axis
    let idx_x = build_replicate_index_map(w, r);

    let mut out = vec![vec![0.0f32; w]; h];

    for y in 0..h {
        let row = &image[y];
        let out_row = &mut out[y];

        for x in 0..w {
            let idx_row = &idx_x[x];
            let mut acc = 0.0f32;

            // branch-free & bounds-check-free
            for i in 0..k {
                acc += row[idx_row[i]] * kernel_x[i];
            }

            out_row[x] = acc;
        }
    }

    out
}

/// 1D vertical pass: convolve each column with `kernel_y` (odd length), replicate borders.
#[inline(always)]
fn convolve_vertical_replicate(
    image: &Vec<Vec<f32>>,
    kernel_y: &Vec<f32>,
) -> Vec<Vec<f32>> {
    let h = image.len();
    let w = image[0].len();
    let k = kernel_y.len();
    let r = k / 2;

    // Precompute replicate indices for y-axis
    let idx_y = build_replicate_index_map(h, r);

    let mut out = vec![vec![0.0f32; w]; h];

    for y in 0..h {
        let out_row = &mut out[y];
        let idx_row = &idx_y[y];

        for x in 0..w {
            let mut acc = 0.0f32;

            // branch-free & bounds-check-free
            for i in 0..k {
                acc += image[idx_row[i]][x] * kernel_y[i];
            }

            out_row[x] = acc;
        }
    }

    out
}

/// Minimal **separable** 2D filter with replicate borders; replacement for cv.sepFilter2D(image, kernelX, kernelY, borderType=1).
#[inline(always)]
pub fn sep_filter_2d(
    image: &Vec<Vec<f32>>,
    kernel_x: &Vec<f32>,
    kernel_y: &Vec<f32>,
) -> Vec<Vec<f32>> {
    let tmp = convolve_horizontal_replicate(image, kernel_x);
    convolve_vertical_replicate(&tmp, kernel_y)
}

/// 3×3 Sobel operator with replicate borders.
/// Returns (dx, dy, magnitude) as three H×W images.
/// - dx uses kernel Gx = [[-1,0,1], [-2,0,2], [-1,0,1]]
/// - dy uses kernel Gy = [[-1,-2,-1], [0,0,0], [1,2,1]]
pub fn sobel_3x3(image: &Vec<Vec<f32>>) -> (Vec<Vec<f32>>, Vec<Vec<f32>>, Vec<Vec<f32>>) {
    // Define Sobel kernels (row-major)
    let gx = vec![
        vec![-1.0,  0.0,  1.0],
        vec![-2.0,  0.0,  2.0],
        vec![-1.0,  0.0,  1.0],
    ];
    let gy = vec![
        vec![-1.0, -2.0, -1.0],
        vec![ 0.0,  0.0,  0.0],
        vec![ 1.0,  2.0,  1.0],
    ];

    let dx = conv2d_replicate(image, &gx);
    let dy = conv2d_replicate(image, &gy);

    // Gradient magnitude = sqrt(dx^2 + dy^2)
    let h = image.len();
    let w = image[0].len();
    let mut mag = vec![vec![0.0f32; w]; h];
    for y in 0..h {
        for x in 0..w {
            let vx = dx[y][x];
            let vy = dy[y][x];
            mag[y][x] = (vx * vx + vy * vy).sqrt();
        }
    }

    (dx, dy, mag)
}

// =============================================================
// Equivalent of _getGaussianDerivs()
// =============================================================
pub fn get_gaussian_derivs(sigma: f32) -> (Vec<f32>, Vec<f32>, Vec<f32>) {
    let length = (sigma * 8.0).floor() as usize + 1;
    let n = length / 2;

    let denom2 = 2.0 * sigma * sigma;

    // ---------------- kernel0 ----------------
    let denom0 = sigma * (2.0 * PI).sqrt();
    let mut kernel0 = vec![0.0f32; length];

    for i in 0..length {
        let pos = i as i32 - n as i32;
        let val = f32::exp(-(pos * pos) as f32 / denom2);
        kernel0[i] = val / denom0;
    }

    // ---------------- kernel1 ----------------
    let denom1 = sigma.powi(3) * (2.0 * PI).sqrt();
    let mut kernel1 = vec![0.0f32; length];

    for i in 0..length {
        let pos = i as i32 - n as i32;
        let val = -(pos as f32) * f32::exp(-(pos * pos) as f32 / denom2);
        kernel1[i] = val / denom1;
    }

    // ---------------- kernel2 ----------------
    let denom2kernel = sigma.powi(5) * (2.0 * PI).sqrt();
    let mut kernel2 = vec![0.0f32; length];

    for i in 0..length {
        let pos = i as i32 - n as i32;
        let val = -(sigma * sigma - (pos * pos) as f32)
            * f32::exp(-(pos * pos) as f32 / denom2);
        kernel2[i] = val / denom2kernel;
    }

    (kernel0, kernel1, kernel2)
}

// =============================================================
// Equivalent of _getMixedDerivs()
// =============================================================
fn get_mixed_derivs(
    image: &Vec<Vec<f32>>,
    kernel0: &Vec<f32>,
    kernel1: &Vec<f32>,
    kernel2: &Vec<f32>,
) -> (Vec<Vec<f32>>, Vec<Vec<f32>>, Vec<Vec<f32>>) 
{
    let dxy = sep_filter_2d(image, kernel1, kernel1);
    let dxx = sep_filter_2d(image, kernel2, kernel0);
    let dyy = sep_filter_2d(image, kernel0, kernel2);
    (dxx, dyy, dxy)
}

// =============================================================
// Equivalent of _getLaplacian()
// =============================================================
fn get_laplacian(
    dxx: &Vec<Vec<f32>>,
    dyy: &Vec<Vec<f32>>,
) -> Vec<Vec<f32>> 
{
    let mut out = zeros_like(dxx);
    for i in 0..dxx.len() {
        for j in 0..dxx[0].len() {
            out[i][j] = dxx[i][j] + dyy[i][j];
        }
    }
    out
}

// =============================================================
// Hessian eigenvalue computation
// =============================================================
fn get_hessian(
    dxx: &Vec<Vec<f32>>,
    dyy: &Vec<Vec<f32>>,
    dxy: &Vec<Vec<f32>>,
) -> (Vec<Vec<f32>>, Vec<Vec<f32>>, Vec<Vec<f32>>) 
{
    let h = dxx.len();
    let w = dxx[0].len();

    let mut hmin = zeros_like(dxx);
    let mut hmax = zeros_like(dxx);
    let mut det  = zeros_like(dxx);

    for i in 0..h {
        for j in 0..w {
            let a = dxx[i][j];
            let b = dxy[i][j];
            let d = dyy[i][j];

            let trace = a + d;
            let delta = (trace * trace - 4.0 * (a * d - b * b)).sqrt();

            let l1 = (trace + delta) / 2.0;
            let l2 = (trace - delta) / 2.0;

            hmin[i][j] = f32::min(l1, l2);
            hmax[i][j] = f32::max(l1, l2);
            det[i][j]  = a * d - b * b;
        }
    }

    (hmin, hmax, det)
}

// =============================================================
// Structure Tensor
// =============================================================
fn get_structure_tensor(
    image: &Vec<Vec<f32>>,
    kernel0: &Vec<f32>,
    compute_coherence: bool,
) -> (Vec<Vec<f32>>, Vec<Vec<f32>>, Vec<Vec<f32>>) 
{
    let (dx, dy, _mag) = sobel_3x3(image);

    let mut dxx = zeros_like(image);
    let mut dyy = zeros_like(image);
    let mut dxy = zeros_like(image);

    for i in 0..image.len() {
        for j in 0..image[0].len() {
            dxx[i][j] = dx[i][j] * dx[i][j];
            dyy[i][j] = dy[i][j] * dy[i][j];
            dxy[i][j] = dx[i][j] * dy[i][j];
        }
    }

    let dxx_f = sep_filter_2d(&dxx, kernel0, kernel0);
    let dyy_f = sep_filter_2d(&dyy, kernel0, kernel0);
    let dxy_f = sep_filter_2d(&dxy, kernel0, kernel0);

    let (st_min, st_max, _) = get_hessian(&dxx_f, &dyy_f, &dxy_f);

    let mut coherence = zeros_like(&st_min);
    if compute_coherence {
        for i in 0..st_min.len() {
            for j in 0..st_min[0].len() {
                let num = st_max[i][j] - st_min[i][j];
                let den = st_max[i][j] + st_min[i][j];
                if den != 0.0 {
                    coherence[i][j] = (num / den).powi(2);
                } else {
                    coherence[i][j] = 0.0;
                }
            }
        }
    }

    (st_min, st_max, coherence)
}


#[inline]
fn get_weighted_stddev(image: &Vec<Vec<f32>>, k0: &Vec<f32>) -> Vec<Vec<f32>> {
    // E[x] via Gaussian smoothing
    let mean = sep_filter_2d(image, k0, k0);

    // E[x^2]
    let h = image.len();
    let w = image[0].len();
    let mut sq = vec![vec![0.0f32; w]; h];
    for y in 0..h {
        for x in 0..w {
            let v = image[y][x];
            sq[y][x] = v * v;
        }
    }
    let mean_sq = sep_filter_2d(&sq, k0, k0);

    // Var = E[x^2] - (E[x])^2; clamp to 0 to avoid tiny negatives
    let mut stddev = vec![vec![0.0f32; w]; h];
    for y in 0..h {
        for x in 0..w {
            let var = (mean_sq[y][x] - mean[y][x] * mean[y][x]).max(0.0);
            stddev[y][x] = var.sqrt();
        }
    }
    stddev
}


/// Compute all features across selected channels and sigmas, stacking each resulting
/// feature layer into a single `[num_layers, H, W]` output, ordered by:
/// channel-major -> sigma-major -> feature-major.
///
/// - `image` is a multi-channel image: shape `[C][H][W]`.
/// - `channel_list` contains channel indices to process.
/// - `feature_list` lists which features to compute (semantics owned by `rust_make_features_single_channel`).
/// - `sigmas` lists sigma (scale) values to apply.
///
/// Returns: a 3D vector where each entry is a 2D layer `[H][W]`.
pub fn all_features_together(
    image: &Vec<Vec<Vec<f32>>>,     // [C][H][W]
    channel_list: &[usize],
    feature_list: &[String],
    sigmas: &[f32],
) -> Vec<Vec<Vec<f32>>> {
    // Optional: validate inputs
    debug_assert!(
        !image.is_empty(),
        "image should have at least one channel"
    );
    if image.is_empty() {
        return Vec::new();
    }

    let h = image[0].len();
    let w = if h > 0 { image[0][0].len() } else { 0 };

    // Reserve roughly (channels * sigmas * features) layers.
    // Exact layer count comes from rust_make_features_single_channel,
    // which typically returns one layer per feature in `feature_list`.
    let mut output: Vec<Vec<Vec<f32>>> =
        Vec::with_capacity(channel_list.len() * sigmas.len() * feature_list.len());

    for &cidx in channel_list {
        // Basic bounds check to avoid panic on bad indices.
        if cidx >= image.len() {
            // You can choose to panic instead if this should be programmer error:
            // panic!("channel index {} out of bounds for image with {} channels", cidx, image.len());
            // For now, skip invalid indices.
            continue;
        }

        let channel_img: &Vec<Vec<f32>> = &image[cidx];

        // Optional: ensure consistent H, W
        debug_assert_eq!(channel_img.len(), h, "all channels must have same height");
        if !channel_img.is_empty() {
            debug_assert_eq!(
                channel_img[0].len(),
                w,
                "all channels must have same width"
            );
        }

        for &s in sigmas {
            // `rust_make_features_single_channel` returns multiple layers (e.g., one per feature).
            let layers_for_sigma: Vec<Vec<Vec<f32>>> =
                rust_make_features_single_channel(channel_img, feature_list, s);

            // Optionally validate sizes of returned layers
            debug_assert!(
                layers_for_sigma.iter().all(|layer| layer.len() == h
                    && (layer.is_empty() || layer[0].len() == w)),
                "feature layer shape must match input channel HxW"
            );

            // Append to the master stack
            output.extend(layers_for_sigma);
        }
    }

    output
}


// Unified features calculator

pub fn rust_make_features_single_channel(
    image: &Vec<Vec<f32>>,
    feature_list: &[String],
    sigma: f32,
) -> Vec<Vec<Vec<f32>>> {
    let (k0, k1, k2) = get_gaussian_derivs(sigma);
    let (dxx, dyy, dxy) = get_mixed_derivs(image, &k0, &k1, &k2);

    let mut layers: Vec<Vec<Vec<f32>>> = Vec::with_capacity(feature_list.len());

    let mut hess_cached: Option<(Vec<Vec<f32>>, Vec<Vec<f32>>, Vec<Vec<f32>>)> = None;
    let mut struct_cached: Option<(Vec<Vec<f32>>, Vec<Vec<f32>>, Vec<Vec<f32>>)> = None;

    for feat in feature_list {
        match feat.as_str() {
            "GAUSSIAN" => {
                let mean = sep_filter_2d(&image, &k0, &k0);
                layers.push(mean);
            }
            "GRADIENT_MAGNITUDE" | "GRAD_MAG" => {
                let (_, _, mag) = sobel_3x3(image);
                layers.push(mag);
            }
            "HESSIAN_DETERMINANT" | "HESSIAN_DET" => {
                if hess_cached.is_none() {
                    hess_cached = Some(get_hessian(&dxx, &dyy, &dxy));
                }
                let (_, _, det) = hess_cached.as_ref().unwrap();
                layers.push(det.clone());
            }
            "HESSIAN_EIGENVALUE_MAX" | "HESSIAN_MAX" => {
                if hess_cached.is_none() {
                    hess_cached = Some(get_hessian(&dxx, &dyy, &dxy));
                }
                let (_, maxv, _) = hess_cached.as_ref().unwrap();
                layers.push(maxv.clone());
            }
            "HESSIAN_EIGENVALUE_MIN" | "HESSIAN_MIN" => {
                if hess_cached.is_none() {
                    hess_cached = Some(get_hessian(&dxx, &dyy, &dxy));
                }
                let (minv, _, _) = hess_cached.as_ref().unwrap();
                layers.push(minv.clone());
            }
            "LAPLACIAN" => {
                layers.push(get_laplacian(&dxx, &dyy));
            }
            "STRUCTURE_TENSOR_COHERENCE" | "STRUCT_CO" => {
                if struct_cached.is_none() {
                    struct_cached = Some(get_structure_tensor(image, &k0, false));
                }
                let (_, _, co) = struct_cached.as_ref().unwrap();
                layers.push(co.clone());
            }
            "STRUCTURE_TENSOR_EIGENVALUE_MAX" | "STRUCT_MAX" => {
                if struct_cached.is_none() {
                    struct_cached = Some(get_structure_tensor(image, &k0, false));
                }
                let (_, maxv, _) = struct_cached.as_ref().unwrap();
                layers.push(maxv.clone());
            }
            "STRUCTURE_TENSOR_EIGENVALUE_MIN" | "STRUCT_MIN" => {
                if struct_cached.is_none() {
                    struct_cached = Some(get_structure_tensor(image, &k0, false));
                }
                let (minv, _, _) = struct_cached.as_ref().unwrap();
                layers.push(minv.clone());
            }
            "WEIGHTED_STD_DEV" | "WGT_STDV" => {
                layers.push(get_weighted_stddev(image, &k0));
            }
            other => panic!("Unknown feature: {}", other),
        }
    }

    layers
}
