# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

## This was modified from a standard GitHub Actions template (original template is MIT license)
#MIT License

#Copyright (c) 2020 GitHub

#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:

#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE. THIS LICENSE DOES NOT GRANT YOU RIGHTS TO USE ANY CONTRIBUTORS'
#NAME, LOGO, OR TRADEMARKS.

name: Python application

on:
  push:
    branches: [ "main" ]
  #push:
  #  branches: ['development']
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv pip-licenses
        uv pip install .[instanseg] --system
        pip freeze
        pip install pytest pytest-cov pytest-xvfb
    - name: Lint with ruff
      run: |
        uvx ruff check palmettobug/ --exit-zero
    - name: pytest
      run: |  
        python -m pytest -p pytest_cov --cov-report xml:coverage.xml --cov=palmettobug tests/  
      # python -m pytest -p pytest_cov --cov-report xml:coverage.xml --cov=palmettobug tests/test_alt_classifiers.py  


#    - uses: codecov/codecov-action@v5

    # just do manual check for any packages listed as UNKNOWN / proprietary for GPL3-compatibility
    - name: Check licenses
      run: pip-licenses
      

#  build2:                   #### having a second build is useful when testing alternate python versions, OS, etc.
#                            ## I know tox is a common way of automating this, but for now manual is fine.
#
#    runs-on: macos-latest
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up Python 3.10
#      uses: actions/setup-python@v3
#      with:
#        python-version: "3.10"
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install uv pytest
#        uv pip install . --system
#    - name: Lint with ruff
#      run: |
#        uvx ruff check palmettobug/ --exit-zero
#    - name: pytest
#      run: |
#        pytest tests/
#        pip freeze
    

